// Code generated by ahp-codegen. DO NOT EDIT.
package client

import (
	"context"
	ahp "github.com/agenthooksprotocol/go-sdk"
	"github.com/agenthooksprotocol/go-sdk/capability"
	"github.com/agenthooksprotocol/go-sdk/content"
	"github.com/agenthooksprotocol/go-sdk/event"
	"github.com/agenthooksprotocol/go-sdk/registration"
	"github.com/agenthooksprotocol/go-sdk/subscription"
	"github.com/agenthooksprotocol/go-sdk/tool"
	"github.com/agenthooksprotocol/go-sdk/transport"
	"time"
)

// compileGeneratedFacadeExample is intentionally not executed: a real application
// supplies its source/manifest and owns actual backend execution. This checks the
// complete public expression and generic inference without network or subprocesses.
func compileGeneratedFacadeExample(ctx context.Context, opts Options) {
	opts.Events = map[string]EventCapabilities{
		"tool.before": {Modes: []Mode{Intercept, Observe}, Capabilities: capability.New([]string{"modify"}, capability.WithInputModification(true, true))},
	}
	c, err := New(registration.New(registration.NewBackend("dev.example.guard",
		transport.NewStdio("guard", ahp.StdioTransportLifecyclePersistent),
		subscription.NewIntercept([]string{"tool.before"}, time.Second, ahp.InterceptSubscriptionFailurePolicyFailClosed, content.NewSelection(ahp.ContentSelectionDefaultOmit)))), opts)
	if err != nil {
		return
	}
	var _ *Hooks = c
	defer c.Close()
	type arguments struct {
		Path string `json:"path"`
	}
	result, err := c.ToolBefore(ctx, event.ToolBeforeInput[arguments]{Path: "/tools/read", Call: ahp.ToolBeforeEventCall{ID: "call-1"}, Tool: tool.NewInput("read", "native", arguments{Path: "file.txt"}, tool.WithInputKind("task"))})
	if err != nil || result == nil {
		return
	}
	var _ arguments = result.Input
}
