// Code generated by ahp-codegen. DO NOT EDIT.
package diagnostic

type Code string

const ProtocolRejection Code = "protocol_rejection"
const RemoteRpc Code = "remote_rpc"
const Transport Code = "transport"
const Cancelled Code = "cancelled"
const DeadlineExceeded Code = "deadline_exceeded"
const Preparation Code = "preparation"
const Capacity Code = "capacity"
