// Code generated by ahp-codegen. DO NOT EDIT.
package ahp_test

import (
	"encoding/json"
	ahp "github.com/agenthooksprotocol/go-sdk"
	"github.com/agenthooksprotocol/go-sdk/capability"
	"github.com/agenthooksprotocol/go-sdk/content"
	"github.com/agenthooksprotocol/go-sdk/diagnostic"
	"github.com/agenthooksprotocol/go-sdk/effect"
	"github.com/agenthooksprotocol/go-sdk/event"
	"github.com/agenthooksprotocol/go-sdk/permission"
	"github.com/agenthooksprotocol/go-sdk/registration"
	"github.com/agenthooksprotocol/go-sdk/state"
	"github.com/agenthooksprotocol/go-sdk/subscription"
	"github.com/agenthooksprotocol/go-sdk/tool"
	"github.com/agenthooksprotocol/go-sdk/transport"
	"io"
	"math"
	"strings"
	"testing"
	"time"
)

func TestGeneratedRegistrationExample(t *testing.T) {
	timeout := 1500 * time.Millisecond
	reg := registration.New(registration.NewBackend("dev.example.guard", transport.NewStdio("guard", ahp.StdioTransportLifecyclePersistent, transport.WithStdioArgs([]string{"--stdio"})), subscription.NewIntercept([]string{"tool.before"}, timeout, ahp.InterceptSubscriptionFailurePolicy("fail-closed"), content.NewSelection(ahp.ContentSelectionDefault("omit")))))
	// Both delivery modes compose on the same backend without constructing union arms.
	intercept := reg.Hooks[0].Subscriptions[0]
	observe := subscription.NewObserve(content.NewSelection("omit"), []string{"tool.before"})
	combined := registration.NewBackend("dev.example.both", transport.NewHttp("https://example.test/hooks"), intercept, registration.WithBackendSubscriptions(intercept, observe))
	if len(combined.Subscriptions) != 2 {
		t.Fatal("required collection option lost subscriptions")
	}
	raw, err := json.Marshal(reg)
	if err != nil {
		t.Fatal(err)
	}
	parsed := ahp.ParseRegistration(raw)
	if !parsed.OK {
		t.Fatalf("registration did not parse: %s", raw)
	}
	denial, err := json.Marshal(effect.NewDeny("not permitted", effect.WithDenyCode("policy")))
	if err != nil || string(denial) != `{"code":"policy","reason":"not permitted","type":"deny"}` {
		t.Fatalf("deny: %s, %v", denial, err)
	}
}

func TestGeneratedDurationChecks(t *testing.T) {
	for _, d := range []time.Duration{0, -time.Millisecond, time.Nanosecond, time.Millisecond + time.Nanosecond, time.Duration(math.MaxInt64), time.Duration(math.MinInt64)} {
		if _, err := subscription.Milliseconds(d); err == nil {
			t.Errorf("accepted inexact/nonpositive duration %v", d)
		}
		if _, err := subscription.NewInterceptDuration([]string{"tool.before"}, d, "fail-closed", content.NewSelection("omit")); err == nil {
			t.Errorf("duration constructor accepted %v", d)
		}
	}
	d := time.Duration(math.MaxInt64/int64(time.Millisecond)) * time.Millisecond
	ms, err := subscription.Milliseconds(d)
	if err != nil || string(ms) != "9223372036854" {
		t.Fatalf("large exact duration: %s %v", ms, err)
	}
	sub, err := subscription.NewInterceptDuration([]string{"tool.before"}, 1500*time.Millisecond, "fail-closed", content.NewSelection("omit"))
	if err != nil || sub.InterceptSubscription.Value.TimeoutMs != "1500" {
		t.Fatalf("conversion: %+v %v", sub, err)
	}
}

func TestGeneratedAutomaticDurationIsExact(t *testing.T) {
	cases := map[time.Duration]string{
		0: "0", time.Nanosecond: "0.000001", -time.Nanosecond: "-0.000001",
		1500 * time.Millisecond: "1500", time.Millisecond + time.Nanosecond: "1.000001",
		time.Duration(math.MaxInt64): "9223372036854.775807", time.Duration(math.MinInt64): "-9223372036854.775808",
	}
	for d, want := range cases {
		got := subscription.NewIntercept([]string{"tool.before"}, d, "fail-closed", content.NewSelection("omit")).InterceptSubscription.Value.TimeoutMs
		if string(got) != want {
			t.Errorf("duration %v: got %q want %q", d, got, want)
		}
	}
}

func TestGeneratedTypedHostProjection(t *testing.T) {
	type args struct {
		Path string `json:"path"`
	}
	input := event.ToolBeforeInput[args]{Path: "/tools/read", Name: "read", Origin: "native", Input: args{Path: "file.txt"}, ToolKind: ahp.Some("task"), CallID: "call-1"}
	raw, err := json.Marshal(input)
	if err != nil {
		t.Fatal(err)
	}
	var object map[string]json.RawMessage
	if err = json.Unmarshal(raw, &object); err != nil {
		t.Fatal(err)
	}
	for _, key := range []string{"source", "type", "manifest", "id", "time", "session"} {
		if _, ok := object[key]; ok {
			t.Errorf("projection emitted SDK-owned or absent %s", key)
		}
	}
	var toolValue struct {
		Input args `json:"input"`
	}
	if err = json.Unmarshal(object["tool"], &toolValue); err != nil || toolValue.Input.Path != "file.txt" {
		t.Fatalf("typed input lost: %s %v", raw, err)
	}
	raw, err = json.Marshal(event.ToolBeforeInput[json.RawMessage]{Input: json.RawMessage(`{"dynamic":true}`)})
	if err != nil {
		t.Fatal(err)
	}
	if !json.Valid(raw) {
		t.Fatal("raw input route invalid")
	}
}

// Metadata options are reusable across payload types and preserve presence,
// including explicit zero values. The constructor never erases the payload.
func TestGeneratedToolInputConstructor(t *testing.T) {
	type arguments struct {
		Path string `json:"path"`
	}
	kind := tool.WithInputKind("")
	typed := tool.NewInput("read", "native", arguments{Path: "file.txt"}, nil, kind)
	var _ arguments = typed.Input
	if !typed.Kind.Present || typed.Kind.Value != "" || typed.Mcp.Present {
		t.Fatal("optional metadata presence lost")
	}
	raw := tool.NewInput("read", "native", json.RawMessage(`{"path":"file.txt"}`), kind)
	a, err := json.Marshal(typed)
	if err != nil {
		t.Fatal(err)
	}
	b, err := json.Marshal(raw)
	if err != nil || string(a) != string(b) {
		t.Fatalf("typed/raw mismatch: %s %s %v", a, b, err)
	}
	absent := tool.NewInput("read", "native", arguments{})
	if absent.Kind.Present || absent.Mcp.Present {
		t.Fatal("absent options materialized")
	}
	mcp := &ahp.ExecutionEventMcp{}
	withMcp := tool.NewInput("read", "mcp", arguments{}, tool.WithInputMcp(mcp))
	if !withMcp.Mcp.Present || withMcp.Mcp.Value != mcp {
		t.Fatal("typed MCP metadata lost")
	}
}

func TestGeneratedConstructorLiteralsAndOptionalDefaults(t *testing.T) {
	sub := subscription.NewObserve(content.NewSelection("omit"), []string{"tool.after"})
	wire := sub.ObserveSubscription.Value
	if wire.Mode != "observe" || !wire.IncludeNative.Present || wire.IncludeNative.Value {
		t.Fatal("literal or schema default lost")
	}
	explicit := subscription.NewObserve(content.NewSelection("omit"), []string{"tool.after"}, subscription.WithObserveIncludeNative(true))
	if !explicit.ObserveSubscription.Value.IncludeNative.Present || !explicit.ObserveSubscription.Value.IncludeNative.Value {
		t.Fatal("default override lost")
	}
	last := subscription.NewObserve(content.NewSelection("omit"), []string{"tool.after"}, subscription.WithObserveIncludeNative(true), subscription.WithObserveIncludeNative(false))
	if !last.ObserveSubscription.Value.IncludeNative.Present || last.ObserveSubscription.Value.IncludeNative.Value {
		t.Fatal("last explicit false lost")
	}
	intercept := subscription.NewIntercept([]string{"tool.before"}, time.Second, "fail-closed", content.NewSelection("omit"))
	if !intercept.InterceptSubscription.Value.IncludeNative.Present || intercept.InterceptSubscription.Value.IncludeNative.Value {
		t.Fatal("intercept default lost")
	}
	a, err := json.Marshal(sub)
	if err != nil {
		t.Fatal(err)
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(a, &fields); err != nil {
		t.Fatal(err)
	}
	if string(fields["includeNative"]) != "false" {
		t.Fatalf("schema default not materialized: %s", a)
	}
	if string(fields["mode"]) != `"observe"` {
		t.Fatalf("wrong union arm/literal: %s", a)
	}
	delete(fields, "includeNative")
	absent, err := json.Marshal(fields)
	if err != nil {
		t.Fatal(err)
	}
	var parsed ahp.ObserveSubscription
	if err := json.Unmarshal(absent, &parsed); err != nil {
		t.Fatal(err)
	}
	if parsed.IncludeNative.Present {
		t.Fatal("parser invented constructor default")
	}
	roundtrip, err := json.Marshal(parsed)
	if err != nil {
		t.Fatal(err)
	}
	var again map[string]json.RawMessage
	if err := json.Unmarshal(roundtrip, &again); err != nil {
		t.Fatal(err)
	}
	if _, exists := again["includeNative"]; exists {
		t.Fatal("parser roundtrip materialized absent default")
	}
}

func TestGeneratedCapabilityHelpers(t *testing.T) {
	absent := capability.New([]string{})
	if absent.Elicitation.Present || absent.Modify.Present || absent.Flow.Present || absent.Inject.Present || len(absent.Effects) != 0 {
		t.Fatal("constructor invented grants")
	}
	empty := capability.New(nil, capability.WithElicitation(ahp.CapabilitiesElicitation{}))
	if !empty.Elicitation.Present || empty.Elicitation.Value.Form.Present || empty.Elicitation.Value.URL.Present {
		t.Fatal("empty elicitation inferred a mode")
	}
	grants := capability.New([]string{"modify", "dev.example.extension"},
		capability.WithInputModification(false, true),
		capability.WithOutputModification(true, false),
		capability.WithElicitationForm(), capability.WithElicitationURL())
	if !grants.Elicitation.Value.Form.Present || !grants.Elicitation.Value.URL.Present {
		t.Fatal("explicit elicitation grant absent")
	}
	raw, err := json.Marshal(grants)
	if err != nil {
		t.Fatal(err)
	}
	var decoded struct {
		Effects     []string                   `json:"effects"`
		Modify      map[string]map[string]bool `json:"modify"`
		Elicitation map[string]map[string]any  `json:"elicitation"`
	}
	if err := json.Unmarshal(raw, &decoded); err != nil {
		t.Fatal(err)
	}
	if len(decoded.Effects) != 2 || decoded.Effects[0] != "modify" || decoded.Effects[1] != "dev.example.extension" {
		t.Fatalf("effects changed: %s", raw)
	}
	input := decoded.Modify["input"]
	if value, present := input["replace"]; !present || value {
		t.Fatalf("explicit false lost: %s", raw)
	}
	if !input["merge"] || !decoded.Modify["output"]["replace"] {
		t.Fatalf("target operation lost: %s", raw)
	}
	for _, mode := range []string{"form", "url"} {
		if value, ok := decoded.Elicitation[mode]; !ok || value == nil || len(value) != 0 {
			t.Fatalf("grant must be explicit empty object: %s", raw)
		}
	}
	overridden := capability.New(nil, capability.WithEffects("allow"), capability.WithEffects("deny"), capability.WithInputModification(true, false), capability.WithInputModification(false, true))
	if len(overridden.Effects) != 1 || overridden.Modify.Value.Input.Value.Replace || !overridden.Modify.Value.Input.Value.Merge {
		t.Fatal("last option did not win")
	}
	noImplicitEffects := capability.New(nil, capability.WithInputModification(false, false), capability.WithElicitationForm())
	if len(noImplicitEffects.Effects) != 0 {
		t.Fatal("nested helper implicitly granted an effect")
	}
	// Options produce independent typed values for each use.
	option := capability.WithInputModification(true, false)
	first, second := capability.New(nil, option), capability.New(nil, option)
	first.Modify.Value.Input.Value.Replace = false
	if !second.Modify.Value.Input.Value.Replace {
		t.Fatal("shared modification backing storage")
	}
}

func TestFunctionalCapabilityComposition(t *testing.T) {
	operations := []capability.ModifyOperation{capability.Replace}
	grant := capability.ModifyInput(operations...)
	operations[0] = capability.ModifyOperation("invalid")
	first, err := capability.Intercept(capability.Deny(), grant, capability.ModifyInput(capability.Merge))
	if err != nil {
		t.Fatal(err)
	}
	second, err := capability.Intercept(grant)
	if err != nil {
		t.Fatal(err)
	}
	if len(first.Modes) != 2 || first.Modes[0] != capability.InterceptMode || first.Modes[1] != capability.ObserveMode {
		t.Fatal(first.Modes)
	}
	combined := first.Capabilities.Modify.Value.Input.Value
	independent := second.Capabilities.Modify.Value.Input.Value
	if !combined.Replace || !combined.Merge || !independent.Replace || independent.Merge {
		t.Fatal("reused grant was mutated")
	}
	if len(first.Capabilities.Effects) != 2 || len(second.Capabilities.Effects) != 1 {
		t.Fatal("effect grants not deduplicated")
	}
	first.Capabilities.Modify.Value.Input.Value.Replace = false
	if !second.Capabilities.Modify.Value.Input.Value.Replace {
		t.Fatal("compositions alias storage")
	}
	for _, invalid := range []capability.Grant{{}, capability.ModifyInput(), capability.ModifyInput("invalid"), capability.InjectContextAppend()} {
		if _, err := capability.Intercept(invalid); err == nil {
			t.Fatal("invalid grant accepted")
		}
	}
	if _, err := capability.Intercept(); err == nil {
		t.Fatal("empty intercept accepted")
	}
	observe := capability.Observe()
	if len(observe.Modes) != 1 || observe.Modes[0] != capability.ObserveMode || observe.Capabilities != nil {
		t.Fatal(observe)
	}
	if _, err := capability.Intercept(capability.FlowStop(), capability.InjectContextAppend(capability.Now), capability.Ask(), capability.ElicitationForm()); err != nil {
		t.Fatal(err)
	}
}

func TestInitialAndTypedEffectOperations(t *testing.T) {
	initial := state.Initial(permission.Allow)
	raw, err := json.Marshal(initial)
	if err != nil {
		t.Fatal(err)
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(raw, &object); err != nil {
		t.Fatal(err)
	}
	if string(object["candidate"]) != "null" || string(object["permission"]) != `"allow"` {
		t.Fatal(string(raw))
	}
	type payload struct {
		Count int `json:"count"`
	}
	candidate, err := state.Candidate(payload{Count: 3})
	if err != nil {
		t.Fatal(err)
	}
	initial = state.Initial(permission.Ask, state.WithCandidate(candidate))
	if string(initial.Candidate.Value.Value) != `{"count":3}` {
		t.Fatal(initial)
	}
	nullPayload, err := state.Candidate[any](nil)
	if err != nil {
		t.Fatal(err)
	}
	if !nullPayload.Valid || string(nullPayload.Value.Value) != "null" {
		t.Fatal("candidate null payload collapsed into no candidate")
	}
	if state.NoCandidate().Valid {
		t.Fatal("no candidate must be null")
	}
	for _, candidate := range []struct {
		value any
		want  string
	}{
		{state.NoCandidate(), `null`}, {nullPayload, `{"value":null}`},
	} {
		encoded, err := json.Marshal(candidate.value)
		if err != nil || string(encoded) != candidate.want {
			t.Fatalf("candidate state: %s %v", encoded, err)
		}
	}
	var missingCandidate ahp.InterceptRequestParamsState
	if json.Unmarshal([]byte(`{"permission":"allow"}`), &missingCandidate) == nil {
		t.Fatal("missing required candidate accepted")
	}
	if _, err := state.Candidate(make(chan int)); err == nil {
		t.Fatal("candidate encoding failure hidden")
	}
	modification, err := effect.ModifyInputReplace(payload{Count: 2})
	if err != nil {
		t.Fatal(err)
	}
	raw, err = json.Marshal(modification)
	if err != nil {
		t.Fatal(err)
	}
	parsed := ahp.ParseEffect(raw)
	if !parsed.OK {
		t.Fatal(parsed.Diagnostics)
	}
	if err := json.Unmarshal(raw, &object); err != nil {
		t.Fatal(err)
	}
	if string(object["target"]) != `"input"` || string(object["operation"]) != `"replace"` || string(object["value"]) != `{"count":2}` {
		t.Fatal(string(raw))
	}
	if _, err := effect.ModifyInputMerge(make(chan int)); err == nil {
		t.Fatal("effect encoding failure hidden")
	}
	if _, err := effect.Return(payload{Count: 3}); err != nil {
		t.Fatal(err)
	}
	var _ diagnostic.Code = diagnostic.ProtocolRejection
	var _ event.Type = event.ToolBefore
}

func TestNamedContentSourceBindingsAreOutOfBand(t *testing.T) {
	source := content.NewSource(io.NopCloser(strings.NewReader("owned content")))
	messages := []*event.ModelVisibleItemInput{
		{ModelVisibleItem: ahp.ModelVisibleItem{Role: "user"}, Parts: []*event.ContentPartInput{{Text: &ahp.TextBodyPart{Text: "inline"}}}},
		{ModelVisibleItem: ahp.ModelVisibleItem{Role: "user"}, Parts: []*event.ContentPartInput{{Text: &ahp.TextBodyPart{Text: "inline"}}, {Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: "image/png"}, Body: source}}}},
		{ModelVisibleItem: ahp.ModelVisibleItem{Role: "assistant"}, Parts: []*event.ContentPartInput{
			{Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: "image/png"}, Body: source}},
			{Text: &ahp.TextBodyPart{Text: "1"}}, {Text: &ahp.TextBodyPart{Text: "2"}}, {Text: &ahp.TextBodyPart{Text: "3"}}, {Text: &ahp.TextBodyPart{Text: "4"}},
			{Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: "image/png"}, Body: source}},
		}},
	}
	input := event.ContextCompactBeforeInput{ItemsHost: &messages}
	sources := input.AHPContentSources()
	if len(sources) != 3 || sources["/items/1/parts/1"] != source || sources["/items/2/parts/0"] != source || sources["/items/2/parts/5"] != source {
		t.Fatal(sources)
	}
	delete(sources, "/items/2/parts/5")
	if input.AHPContentSources()["/items/2/parts/5"] != source {
		t.Fatal("binding map aliases caller state")
	}
	raw, err := json.Marshal(input)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(raw), "owned content") || strings.Contains(string(raw), "Source") {
		t.Fatal("source serialized into protocol", string(raw))
	}
	before := event.ToolBeforeInput[map[string]int]{
		CallID: "call", Name: "run", Origin: "native", Path: "/tool", Input: map[string]int{"count": 1},
		ItemsSources: []*content.Source{source},
	}
	if before.AHPContentSources()["/items/0"] != source {
		t.Fatal("generic input lost source binding")
	}
	raw, err = json.Marshal(before)
	if err != nil {
		t.Fatal(err)
	}
	var value map[string]json.RawMessage
	if err := json.Unmarshal(raw, &value); err != nil {
		t.Fatal(err)
	}
	var call struct {
		ID string `json:"id"`
	}
	if err := json.Unmarshal(value["call"], &call); err != nil || call.ID != "call" {
		t.Fatalf("canonical call mapping: %s %v", raw, err)
	}
	if _, exists := value["callId"]; exists {
		t.Fatal("flat host field leaked onto wire")
	}
}

func TestContinuationCountsRejectInvalidComposition(t *testing.T) {
	for _, pair := range [][2]int64{{-1, 0}, {0, -1}, {9007199254740992, 0}, {0, 9007199254740992}} {
		if _, err := capability.Intercept(capability.FlowContinue(pair[0], pair[1])); err == nil {
			t.Fatalf("invalid continuation counts accepted: %v", pair)
		}
	}
	for _, pair := range [][2]int64{{0, 0}, {1, 2}, {9007199254740991, 9007199254740991}} {
		if _, err := capability.Intercept(capability.FlowContinue(pair[0], pair[1])); err != nil {
			t.Fatal(err)
		}
	}
}

// The host adapter must not consume or close an owned stream during projection.
type forbiddenContentReader struct{ reads, closes int }

func (r *forbiddenContentReader) Read([]byte) (int, error) { r.reads++; return 0, io.ErrUnexpectedEOF }
func (r *forbiddenContentReader) Close() error             { r.closes++; return io.ErrClosedPipe }

func TestDirectOwnedAttachmentHostInput(t *testing.T) {
	reader := &forbiddenContentReader{}
	source := content.NewSource(reader)
	defer func() {
		if reader.reads != 0 || reader.closes != 0 {
			t.Fatal("host adapter consumed source")
		}
	}()
	messages := []*event.ModelVisibleItemInput{{
		ModelVisibleItem: ahp.ModelVisibleItem{ID: "message-id", Role: "user", AdditionalProperties: map[string]json.RawMessage{"vendor": json.RawMessage(`{"retained":true}`)}},
		Parts: []*event.ContentPartInput{
			{Text: &ahp.TextBodyPart{Text: "inline text"}},
			{Attachment: &event.AttachmentBodyInput{
				AttachmentBodyPart: ahp.AttachmentBodyPart{ID: "part-id", Category: ahp.Some("image"), MediaType: "image/png", AdditionalProperties: map[string]json.RawMessage{"vendorPart": json.RawMessage(`7`)}},
				Body:               source,
			}},
		},
	}}
	input := event.ContextCompactBeforeInput{ItemsHost: &messages}
	sources := input.AHPContentSources()
	if len(sources) != 1 || sources["/items/0/parts/1"] != source {
		t.Fatal(sources)
	}
	delete(sources, "/items/0/parts/1")
	if input.AHPContentSources()["/items/0/parts/1"] != source {
		t.Fatal("source map aliases host state")
	}
	raw, err := json.Marshal(input)
	if err != nil {
		t.Fatal(err)
	}
	var encoded map[string]any
	if err := json.Unmarshal(raw, &encoded); err != nil {
		t.Fatal(err)
	}
	message := encoded["items"].([]any)[0].(map[string]any)
	if message["id"] != "message-id" || message["role"] != "user" || message["vendor"].(map[string]any)["retained"] != true {
		t.Fatal(message)
	}
	parts := message["parts"].([]any)
	text := parts[0].(map[string]any)
	if text["kind"] != "text" || text["selection"] != "body" || text["text"] != "inline text" || text["id"] == "" || text["synthesized"] != true {
		t.Fatal(text)
	}
	attachment := parts[1].(map[string]any)
	if attachment["id"] != "part-id" || attachment["category"] != "image" || attachment["mediaType"] != "image/png" || attachment["selection"] != "body" || attachment["vendorPart"] != float64(7) {
		t.Fatal(attachment)
	}
	if attachment["body"].(map[string]any)["ref"] != "ahp:owned:pending" {
		t.Fatal(attachment)
	}
	for _, encodedPart := range parts {
		partRaw, err := json.Marshal(encodedPart)
		if err != nil {
			t.Fatal(err)
		}
		var canonical ahp.ContentItem
		if err := json.Unmarshal(partRaw, &canonical); err != nil {
			t.Fatalf("host part is not canonical: %s: %v", partRaw, err)
		}
	}
	for _, local := range []string{"Reader", "Descriptor", "AttachmentBodyPart", "Host", "Source"} {
		if strings.Contains(string(raw), local) {
			t.Fatalf("local member %s serialized: %s", local, raw)
		}
	}
	// Only missing identities are retained on their host objects; other metadata is unchanged.
	if messages[0].Parts[0].Text.ID != text["id"] || messages[0].Parts[1].Attachment.Selection != "" {
		t.Fatal("host projection did not retain identity or mutated metadata")
	}
	input.AHPContentSources()
	rawAgain, err := json.Marshal(input)
	if err != nil || string(rawAgain) != string(raw) {
		t.Fatalf("encoding changed identities: %s / %s: %v", raw, rawAgain, err)
	}
}

func TestOwnedHostNestedMessageAndScope(t *testing.T) {
	reader := &forbiddenContentReader{}
	source := content.NewSource(reader)
	defer func() {
		if reader.reads != 0 || reader.closes != 0 {
			t.Fatal("host adapter consumed source")
		}
	}()
	part := &event.ContentPartInput{Attachment: &event.AttachmentBodyInput{
		AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: "application/octet-stream", Selection: "body"},
		Body:               source, Descriptor: &ahp.ContentReference{Ref: "content://supplied"},
	}}
	input := event.UserMessageInboundInput{MessageHost: &event.UserMessageInboundEventMessageInput{
		UserMessageInboundEventMessage: ahp.UserMessageInboundEventMessage{Channel: "chat", Sender: "human"},
		Messages: []event.UserMessageInboundEventMessageMessagesItemInput{
			{UserMessageInboundEventMessageMessagesItem: ahp.UserMessageInboundEventMessageMessagesItem{Role: "user"}, Parts: []*event.ContentPartInput{{Text: &ahp.TextBodyPart{ID: "text-id", Text: "hello"}}, part}},
		},
	}}
	if input.AHPContentSources()["/message/messages/0/parts/1"] != source {
		t.Fatal(input.AHPContentSources())
	}
	plannedMessageID := input.MessageHost.Messages[0].ID
	plannedPartID := part.Attachment.ID
	if plannedMessageID == "" || plannedPartID == "" {
		t.Fatal("planning did not retain generated identities")
	}
	raw, err := json.Marshal(input)
	if err != nil {
		t.Fatal(err)
	}
	var encoded map[string]any
	if err := json.Unmarshal(raw, &encoded); err != nil {
		t.Fatal(err)
	}
	wrapper := encoded["message"].(map[string]any)
	if wrapper["channel"] != "chat" || wrapper["sender"] != "human" {
		t.Fatal(wrapper)
	}
	message := wrapper["messages"].([]any)[0].(map[string]any)
	if message["id"] != plannedMessageID || message["synthesized"] != true {
		t.Fatal(message)
	}
	attachment := message["parts"].([]any)[1].(map[string]any)
	if attachment["id"] == "" || attachment["synthesized"] != true || attachment["body"].(map[string]any)["ref"] != "content://supplied" {
		t.Fatal(attachment)
	}
	input.AHPContentSources()
	again, err := json.Marshal(input)
	if err != nil || string(again) != string(raw) || part.Attachment.ID != plannedPartID {
		t.Fatalf("unstable nested identity: %s / %s: %v", raw, again, err)
	}
	// The generic tool payload is not a declared content slot.
	outside := event.ToolBeforeInput[*event.ContentPartInput]{Input: part}
	if len(outside.AHPContentSources()) != 0 {
		t.Fatal("scanned arbitrary tool payload")
	}
	parts := []*event.ContentPartInput{nil, part}
	outside.ItemsHost = &parts
	if outside.AHPContentSources()["/items/1"] != source || len(outside.AHPContentSources()) != 1 {
		t.Fatal(outside.AHPContentSources())
	}
	// Explicit empty host collections override wire collections and advanced bindings.
	empty := []*event.ContentPartInput{}
	outside.ItemsHost = &empty
	outside.ItemsSources = []*content.Source{source}
	if len(outside.AHPContentSources()) != 0 {
		t.Fatal("stale advanced binding survived host override")
	}
	raw, err = json.Marshal(outside)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, &encoded); err != nil {
		t.Fatal(err)
	}
	if len(encoded["items"].([]any)) != 0 {
		t.Fatal("empty host override lost")
	}
}

func TestOwnedHostPartAlternatives(t *testing.T) {
	for _, part := range []event.ContentPartInput{{}, {Wire: &ahp.ContentItem{}, Text: &ahp.TextBodyPart{Text: "conflict"}}} {
		if _, err := json.Marshal(part); err == nil {
			t.Fatal("ambiguous or missing host part accepted")
		}
	}
	wire := &ahp.ContentItem{Unknown: json.RawMessage(`{"kind":"vendor","opaque":true}`)}
	raw, err := json.Marshal(event.ContentPartInput{Wire: wire})
	if err != nil {
		t.Fatal(err)
	}
	if string(raw) != `{"kind":"vendor","opaque":true}` {
		t.Fatal(string(raw))
	}
}

func TestOwnedAttachmentValidationAndIdentity(t *testing.T) {
	source := content.NewSource(&forbiddenContentReader{})
	for _, media := range []string{"", "text/plain", "TEXT/HTML; charset=utf-8", "application/json", "application/json; charset=utf-8", "application/problem+json", "IMAGE/custom+JSON", "not a media type"} {
		t.Run(media, func(t *testing.T) {
			part := event.ContentPartInput{Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: media}, Body: source}}
			if _, err := json.Marshal(part); err == nil {
				t.Fatalf("accepted owned media type %q", media)
			}
		})
	}
	for _, selection := range []ahp.AttachmentBodyPartSelection{"gap", "metadata", "omit"} {
		part := event.ContentPartInput{Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: "image/png", Selection: selection}, Body: source}}
		if _, err := json.Marshal(part); err == nil {
			t.Fatalf("accepted selection %q", selection)
		}
	}
	for _, selection := range []ahp.TextBodyPartSelection{"gap", "metadata", "omit"} {
		if _, err := json.Marshal(event.ContentPartInput{Text: &ahp.TextBodyPart{Text: "inline", Selection: selection}}); err == nil {
			t.Fatalf("accepted text body selection %q", selection)
		}
	}
	invalidText := &ahp.TextBodyPart{Text: "inline", Synthesized: ahp.Some(false)}
	invalidAttachment := &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: "image/png", Synthesized: ahp.Some(false)}, Body: source}
	for _, part := range []event.ContentPartInput{{Text: invalidText}, {Attachment: invalidAttachment}} {
		if _, err := json.Marshal(part); err == nil {
			t.Fatal("missing id silently replaced synthesized=false")
		}
	}
	if invalidText.ID != "" || invalidText.Synthesized.Value || invalidAttachment.ID != "" || invalidAttachment.Synthesized.Value {
		t.Fatal("inconsistent identity was mutated")
	}
	messages := []*event.ModelVisibleItemInput{{ModelVisibleItem: ahp.ModelVisibleItem{Role: "user", Synthesized: ahp.Some(false)}, Parts: []*event.ContentPartInput{{Text: &ahp.TextBodyPart{ID: "text", Text: "inline"}}}}}
	input := event.ContextCompactBeforeInput{ItemsHost: &messages}
	input.AHPContentSources()
	if _, err := json.Marshal(input); err == nil {
		t.Fatal("missing message id silently replaced synthesized=false")
	}
	if messages[0].ID != "" || messages[0].Synthesized.Value {
		t.Fatal("message false provenance was mutated")
	}
	// Explicit identities and provenance remain authoritative, including false.
	preserved := &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{ID: "supplied", Synthesized: ahp.Some(false), MediaType: "image/png"}, Body: source}
	part := event.ContentPartInput{Attachment: preserved}
	raw, err := json.Marshal(part)
	if err != nil {
		t.Fatal(err)
	}
	again, err := json.Marshal(part)
	if err != nil || string(raw) != string(again) {
		t.Fatal("explicit identity changed")
	}
	if preserved.ID != "supplied" || !preserved.Synthesized.Present || preserved.Synthesized.Value {
		t.Fatal("explicit provenance changed")
	}
	fresh := event.ContentPartInput{Text: &ahp.TextBodyPart{Text: "same"}}
	other := event.ContentPartInput{Text: &ahp.TextBodyPart{Text: "same"}}
	raw, err = json.Marshal(fresh)
	if err != nil {
		t.Fatal(err)
	}
	again, err = json.Marshal(fresh)
	if err != nil || string(raw) != string(again) {
		t.Fatal("new text identity not stable")
	}
	if _, err := json.Marshal(other); err != nil {
		t.Fatal(err)
	}
	if fresh.Text.ID == other.Text.ID {
		t.Fatal("distinct objects share synthesized identity")
	}
}

func TestHostContentStructuralValidation(t *testing.T) {
	source := content.NewSource(&forbiddenContentReader{})
	type hostCase struct {
		name string
		part event.ContentPartInput
	}
	cases := []hostCase{
		{"text-kind", event.ContentPartInput{Text: &ahp.TextBodyPart{Kind: "attachment", Text: "inline"}}},
		{"text-media", event.ContentPartInput{Text: &ahp.TextBodyPart{MediaType: "text/html", Text: "inline"}}},
		{"text-json", event.ContentPartInput{Text: &ahp.TextBodyPart{MediaType: "application/json", Text: "inline"}}},
		{"text-category", event.ContentPartInput{Text: &ahp.TextBodyPart{Category: ahp.Some(""), Text: "inline"}}},
		{"attachment-kind", event.ContentPartInput{Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{Kind: "text", MediaType: "image/png"}, Body: source}}},
		{"attachment-category", event.ContentPartInput{Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{Category: ahp.Some(""), MediaType: "image/png"}, Body: source}}},
	}
	for _, prop := range []string{"size", "sha256"} {
		value := json.RawMessage(`0`)
		if prop == "sha256" {
			value = json.RawMessage(`"` + strings.Repeat("a", 64) + `"`)
		}
		evidence := map[string]json.RawMessage{prop: value}
		cases = append(cases,
			hostCase{"text-" + prop, event.ContentPartInput{Text: &ahp.TextBodyPart{Text: "inline", AdditionalProperties: evidence}}},
			hostCase{"attachment-" + prop, event.ContentPartInput{Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: "image/png", AdditionalProperties: evidence}, Body: source}}},
		)
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := json.Marshal(tc.part); err == nil {
				t.Fatal("invalid host projection accepted")
			}
		})
	}
	// Ordinary unknown metadata is retained under the decoder's extension rules.
	part := event.ContentPartInput{Text: &ahp.TextBodyPart{ID: "explicit", Category: ahp.Some("note"), Text: "inline", AdditionalProperties: map[string]json.RawMessage{"vendor": json.RawMessage(`{"retained":true}`)}}}
	raw, err := json.Marshal(part)
	if err != nil {
		t.Fatal(err)
	}
	var canonical ahp.ContentItem
	if err := json.Unmarshal(raw, &canonical); err != nil || !canonical.TextBodyPart.Present {
		t.Fatalf("valid host part rejected: %s: %v", raw, err)
	}
	if string(canonical.TextBodyPart.Value.AdditionalProperties["vendor"]) != `{"retained":true}` {
		t.Fatal("ordinary metadata lost")
	}
	// The advanced wire alternative deliberately retains its existing semantics.
	wire := &ahp.ContentItem{Unknown: json.RawMessage(`{"kind":"vendor","size":7,"category":""}`)}
	want, err := json.Marshal(wire)
	if err != nil {
		t.Fatal(err)
	}
	got, err := json.Marshal(event.ContentPartInput{Wire: wire})
	if err != nil || string(got) != string(want) {
		t.Fatal("wire pass-through changed")
	}
}

func TestHostContainerValidation(t *testing.T) {
	reader := &forbiddenContentReader{}
	source := content.NewSource(reader)
	defer func() {
		if reader.reads != 0 || reader.closes != 0 {
			t.Fatal("container validation consumed source")
		}
	}()
	owned := &event.ContentPartInput{Attachment: &event.AttachmentBodyInput{AttachmentBodyPart: ahp.AttachmentBodyPart{MediaType: "image/png"}, Body: source}}
	nilMessages := []*event.ModelVisibleItemInput(nil)
	nullMessage := []*event.ModelVisibleItemInput{nil}
	nilParts := []*event.ContentPartInput(nil)
	nullParts := []*event.ContentPartInput{owned, nil}
	invalid := []struct {
		name  string
		input any
	}{
		{"nil-root-messages", event.ContextCompactBeforeInput{ItemsHost: &nilMessages}},
		{"null-message-entry", event.ContextCompactBeforeInput{ItemsHost: &nullMessage}},
		{"nil-root-parts", event.ToolBeforeInput[int]{ItemsHost: &nilParts}},
		{"null-root-part-entry", event.ToolBeforeInput[int]{ItemsHost: &nullParts}},
		{"nil-message-parts", &event.ModelVisibleItemInput{ModelVisibleItem: ahp.ModelVisibleItem{Role: "user"}}},
		{"null-message-part-entry", &event.ModelVisibleItemInput{ModelVisibleItem: ahp.ModelVisibleItem{Role: "user"}, Parts: nullParts}},
		{"nil-nested-messages", event.UserMessageInboundInput{MessageHost: &event.UserMessageInboundEventMessageInput{UserMessageInboundEventMessage: ahp.UserMessageInboundEventMessage{Channel: "chat", Sender: "human"}}}},
		{"nil-nested-parts", event.UserMessageInboundInput{MessageHost: &event.UserMessageInboundEventMessageInput{UserMessageInboundEventMessage: ahp.UserMessageInboundEventMessage{Channel: "chat", Sender: "human"}, Messages: []event.UserMessageInboundEventMessageMessagesItemInput{{UserMessageInboundEventMessageMessagesItem: ahp.UserMessageInboundEventMessageMessagesItem{Role: "user"}}}}}},
	}
	for _, tc := range invalid {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := json.Marshal(tc.input); err == nil {
				t.Fatal("invalid host container accepted")
			}
		})
	}
	for _, role := range []ahp.ModelVisibleItemRole{"", "future", "human"} {
		message := &event.ModelVisibleItemInput{ModelVisibleItem: ahp.ModelVisibleItem{Role: role}, Parts: []*event.ContentPartInput{owned}}
		if _, err := json.Marshal(message); err == nil {
			t.Fatalf("accepted noncanonical role %q", role)
		}
	}
	nested := &event.UserMessageInboundEventMessageInput{UserMessageInboundEventMessage: ahp.UserMessageInboundEventMessage{Channel: "chat", Sender: "human"}, Messages: []event.UserMessageInboundEventMessageMessagesItemInput{{UserMessageInboundEventMessageMessagesItem: ahp.UserMessageInboundEventMessageMessagesItem{Role: "future"}, Parts: []*event.ContentPartInput{owned}}}}
	if _, err := json.Marshal(nested); err == nil {
		t.Fatal("accepted noncanonical nested role")
	}
	// Empty, non-nil arrays and every canonical role remain valid.
	for _, role := range []ahp.ModelVisibleItemRole{"system", "developer", "user", "assistant", "tool"} {
		message := &event.ModelVisibleItemInput{ModelVisibleItem: ahp.ModelVisibleItem{Role: role}, Parts: []*event.ContentPartInput{}}
		if _, err := json.Marshal(message); err != nil {
			t.Fatalf("rejected canonical role %q: %v", role, err)
		}
	}
	valid := []*event.ModelVisibleItemInput{{ModelVisibleItem: ahp.ModelVisibleItem{Role: "user"}, Parts: []*event.ContentPartInput{owned}}}
	input := event.ContextCompactBeforeInput{ItemsHost: &valid}
	input.AHPContentSources()
	if _, err := json.Marshal(input); err != nil {
		t.Fatal(err)
	}
	// Parallel advanced source bindings intentionally remain sparse. Wire-only
	// encoding keeps its prior behavior and does not acquire host validation.
	advanced := event.ToolBeforeInput[any]{ItemsSources: []*content.Source{nil, source}}
	if advanced.AHPContentSources()["/items/1"] != source {
		t.Fatal("sparse advanced binding lost")
	}
	if _, err := json.Marshal(advanced); err != nil {
		t.Fatal("wire-only behavior changed", err)
	}
}
