// Code generated by ahp-codegen. DO NOT EDIT.
package ahp_test

import (
	"encoding/json"
	ahp "github.com/agenthooksprotocol/go-sdk"
	"github.com/agenthooksprotocol/go-sdk/content"
	"github.com/agenthooksprotocol/go-sdk/effect"
	"github.com/agenthooksprotocol/go-sdk/event"
	"github.com/agenthooksprotocol/go-sdk/registration"
	"github.com/agenthooksprotocol/go-sdk/subscription"
	"github.com/agenthooksprotocol/go-sdk/tool"
	"github.com/agenthooksprotocol/go-sdk/transport"
	"math"
	"testing"
	"time"
)

func TestGeneratedRegistrationExample(t *testing.T) {
	timeout := 1500 * time.Millisecond
	reg := registration.New(registration.NewBackend("dev.example.guard", transport.NewStdio("guard", ahp.StdioTransportLifecyclePersistent, transport.WithStdioArgs([]string{"--stdio"})), subscription.NewIntercept([]string{"tool.before"}, timeout, ahp.InterceptSubscriptionFailurePolicy("fail-closed"), content.NewSelection(ahp.ContentSelectionDefault("omit")))))
	// Both delivery modes compose on the same backend without constructing union arms.
	intercept := reg.Hooks[0].Subscriptions[0]
	observe := subscription.NewObserve(content.NewSelection("omit"), []string{"tool.before"})
	combined := registration.NewBackend("dev.example.both", transport.NewHttp("https://example.test/hooks"), intercept, registration.WithBackendSubscriptions(intercept, observe))
	if len(combined.Subscriptions) != 2 {
		t.Fatal("required collection option lost subscriptions")
	}
	raw, err := json.Marshal(reg)
	if err != nil {
		t.Fatal(err)
	}
	parsed := ahp.ParseRegistration(raw)
	if !parsed.OK {
		t.Fatalf("registration did not parse: %s", raw)
	}
	denial, err := json.Marshal(effect.NewDeny("not permitted", effect.WithDenyCode("policy")))
	if err != nil || string(denial) != `{"code":"policy","reason":"not permitted","type":"deny"}` {
		t.Fatalf("deny: %s, %v", denial, err)
	}
}

func TestGeneratedDurationChecks(t *testing.T) {
	for _, d := range []time.Duration{0, -time.Millisecond, time.Nanosecond, time.Millisecond + time.Nanosecond, time.Duration(math.MaxInt64), time.Duration(math.MinInt64)} {
		if _, err := subscription.Milliseconds(d); err == nil {
			t.Errorf("accepted inexact/nonpositive duration %v", d)
		}
		if _, err := subscription.NewInterceptDuration([]string{"tool.before"}, d, "fail-closed", content.NewSelection("omit")); err == nil {
			t.Errorf("duration constructor accepted %v", d)
		}
	}
	d := time.Duration(math.MaxInt64/int64(time.Millisecond)) * time.Millisecond
	ms, err := subscription.Milliseconds(d)
	if err != nil || string(ms) != "9223372036854" {
		t.Fatalf("large exact duration: %s %v", ms, err)
	}
	sub, err := subscription.NewInterceptDuration([]string{"tool.before"}, 1500*time.Millisecond, "fail-closed", content.NewSelection("omit"))
	if err != nil || sub.InterceptSubscription.Value.TimeoutMs != "1500" {
		t.Fatalf("conversion: %+v %v", sub, err)
	}
}

func TestGeneratedAutomaticDurationIsExact(t *testing.T) {
	cases := map[time.Duration]string{
		0: "0", time.Nanosecond: "0.000001", -time.Nanosecond: "-0.000001",
		1500 * time.Millisecond: "1500", time.Millisecond + time.Nanosecond: "1.000001",
		time.Duration(math.MaxInt64): "9223372036854.775807", time.Duration(math.MinInt64): "-9223372036854.775808",
	}
	for d, want := range cases {
		got := subscription.NewIntercept([]string{"tool.before"}, d, "fail-closed", content.NewSelection("omit")).InterceptSubscription.Value.TimeoutMs
		if string(got) != want {
			t.Errorf("duration %v: got %q want %q", d, got, want)
		}
	}
}

func TestGeneratedTypedHostProjection(t *testing.T) {
	type args struct {
		Path string `json:"path"`
	}
	input := event.ToolBeforeInput[args]{Path: "/tools/read", Tool: tool.NewInput("read", "native", args{Path: "file.txt"}, tool.WithInputKind("task")), Call: ahp.ToolBeforeEventCall{ID: "call-1"}}
	raw, err := json.Marshal(input)
	if err != nil {
		t.Fatal(err)
	}
	var object map[string]json.RawMessage
	if err = json.Unmarshal(raw, &object); err != nil {
		t.Fatal(err)
	}
	for _, key := range []string{"source", "type", "manifest", "id", "time", "session"} {
		if _, ok := object[key]; ok {
			t.Errorf("projection emitted SDK-owned or absent %s", key)
		}
	}
	var toolValue struct {
		Input args `json:"input"`
	}
	if err = json.Unmarshal(object["tool"], &toolValue); err != nil || toolValue.Input.Path != "file.txt" {
		t.Fatalf("typed input lost: %s %v", raw, err)
	}
	raw, err = json.Marshal(event.ToolBeforeInput[json.RawMessage]{Tool: tool.Input[json.RawMessage]{Input: json.RawMessage(`{"dynamic":true}`)}})
	if err != nil {
		t.Fatal(err)
	}
	if !json.Valid(raw) {
		t.Fatal("raw input route invalid")
	}
}

// Metadata options are reusable across payload types and preserve presence,
// including explicit zero values. The constructor never erases the payload.
func TestGeneratedToolInputConstructor(t *testing.T) {
	type arguments struct {
		Path string `json:"path"`
	}
	kind := tool.WithInputKind("")
	typed := tool.NewInput("read", "native", arguments{Path: "file.txt"}, nil, kind)
	var _ arguments = typed.Input
	if !typed.Kind.Present || typed.Kind.Value != "" || typed.Mcp.Present {
		t.Fatal("optional metadata presence lost")
	}
	raw := tool.NewInput("read", "native", json.RawMessage(`{"path":"file.txt"}`), kind)
	a, err := json.Marshal(typed)
	if err != nil {
		t.Fatal(err)
	}
	b, err := json.Marshal(raw)
	if err != nil || string(a) != string(b) {
		t.Fatalf("typed/raw mismatch: %s %s %v", a, b, err)
	}
	absent := tool.NewInput("read", "native", arguments{})
	if absent.Kind.Present || absent.Mcp.Present {
		t.Fatal("absent options materialized")
	}
	mcp := &ahp.ExecutionEventMcp{}
	withMcp := tool.NewInput("read", "mcp", arguments{}, tool.WithInputMcp(mcp))
	if !withMcp.Mcp.Present || withMcp.Mcp.Value != mcp {
		t.Fatal("typed MCP metadata lost")
	}
}

func TestGeneratedConstructorLiteralsAndOptionalDefaults(t *testing.T) {
	sub := subscription.NewObserve(content.NewSelection("omit"), []string{"tool.after"})
	wire := sub.ObserveSubscription.Value
	if wire.Mode != "observe" || !wire.IncludeNative.Present || wire.IncludeNative.Value {
		t.Fatal("literal or schema default lost")
	}
	explicit := subscription.NewObserve(content.NewSelection("omit"), []string{"tool.after"}, subscription.WithObserveIncludeNative(true))
	if !explicit.ObserveSubscription.Value.IncludeNative.Present || !explicit.ObserveSubscription.Value.IncludeNative.Value {
		t.Fatal("default override lost")
	}
	last := subscription.NewObserve(content.NewSelection("omit"), []string{"tool.after"}, subscription.WithObserveIncludeNative(true), subscription.WithObserveIncludeNative(false))
	if !last.ObserveSubscription.Value.IncludeNative.Present || last.ObserveSubscription.Value.IncludeNative.Value {
		t.Fatal("last explicit false lost")
	}
	intercept := subscription.NewIntercept([]string{"tool.before"}, time.Second, "fail-closed", content.NewSelection("omit"))
	if !intercept.InterceptSubscription.Value.IncludeNative.Present || intercept.InterceptSubscription.Value.IncludeNative.Value {
		t.Fatal("intercept default lost")
	}
	a, err := json.Marshal(sub)
	if err != nil {
		t.Fatal(err)
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(a, &fields); err != nil {
		t.Fatal(err)
	}
	if string(fields["includeNative"]) != "false" {
		t.Fatalf("schema default not materialized: %s", a)
	}
	if string(fields["mode"]) != `"observe"` {
		t.Fatalf("wrong union arm/literal: %s", a)
	}
	delete(fields, "includeNative")
	absent, err := json.Marshal(fields)
	if err != nil {
		t.Fatal(err)
	}
	var parsed ahp.ObserveSubscription
	if err := json.Unmarshal(absent, &parsed); err != nil {
		t.Fatal(err)
	}
	if parsed.IncludeNative.Present {
		t.Fatal("parser invented constructor default")
	}
	roundtrip, err := json.Marshal(parsed)
	if err != nil {
		t.Fatal(err)
	}
	var again map[string]json.RawMessage
	if err := json.Unmarshal(roundtrip, &again); err != nil {
		t.Fatal(err)
	}
	if _, exists := again["includeNative"]; exists {
		t.Fatal("parser roundtrip materialized absent default")
	}
}
