// Code generated by ahp-codegen. DO NOT EDIT.
package event

import ahp "github.com/agenthooksprotocol/go-sdk"
import "encoding/json"
import "github.com/agenthooksprotocol/go-sdk/tool"

type ConfigChangeAfterInput struct {
	Change        ahp.ConfigChangeAfterEventChange                   `json:"change"`
	Extensions    ahp.Optional[*ahp.Extensions]                      `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ConfigChangeAfterEventGapsItem] `json:"gaps"`
	ID            string                                             `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                   `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                     `json:"native"`
	ParentEventId ahp.Optional[string]                               `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                         `json:"session"`
	Synthesized   ahp.Optional[bool]                                 `json:"synthesized"`
	Time          string                                             `json:"time"`
	Turn          ahp.Optional[ahp.ConfigChangeAfterEventTurn]       `json:"turn"`
}

func (v ConfigChangeAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["change"] = v.Change
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ConfigChangeBeforeInput struct {
	Change        ahp.ConfigChangeBeforeEventChange                   `json:"change"`
	Extensions    ahp.Optional[*ahp.Extensions]                       `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ConfigChangeBeforeEventGapsItem] `json:"gaps"`
	ID            string                                              `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                    `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                      `json:"native"`
	ParentEventId ahp.Optional[string]                                `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                          `json:"session"`
	Synthesized   ahp.Optional[bool]                                  `json:"synthesized"`
	Time          string                                              `json:"time"`
	Turn          ahp.Optional[ahp.ConfigChangeBeforeEventTurn]       `json:"turn"`
}

func (v ConfigChangeBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["change"] = v.Change
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ContextCompactAfterInput struct {
	Execution     *ahp.ExecutionEventExecution                         `json:"execution"`
	Extensions    ahp.Optional[*ahp.Extensions]                        `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ContextCompactAfterEventGapsItem] `json:"gaps"`
	ID            string                                               `json:"id"`
	Items         ahp.Optional[[]*ahp.ModelVisibleItem]                `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                       `json:"native"`
	ParentEventId ahp.Optional[string]                                 `json:"parentEventId"`
	Removed       []ahp.ContextCompactAfterEventRemovedItem            `json:"removed"`
	Session       ahp.Optional[*ahp.Session]                           `json:"session"`
	Summary       *ahp.ModelVisibleItem                                `json:"summary"`
	Synthesized   ahp.Optional[bool]                                   `json:"synthesized"`
	Time          string                                               `json:"time"`
	TokenCounts   ahp.Optional[*ahp.ExecutionEventTokencounts]         `json:"tokenCounts"`
	Turn          ahp.Optional[ahp.ContextCompactAfterEventTurn]       `json:"turn"`
}

func (v ContextCompactAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["execution"] = v.Execution
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["removed"] = v.Removed
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	fields["summary"] = v.Summary
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.TokenCounts.Present {
		fields["tokenCounts"] = v.TokenCounts.Value
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ContextCompactBeforeInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]                `json:"extensions"`
	Gaps          ahp.Optional[[]json.RawMessage]              `json:"gaps"`
	ID            string                                       `json:"id"`
	Instructions  ahp.Optional[*ahp.ContentItem]               `json:"instructions"`
	Items         []*ahp.ModelVisibleItem                      `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]               `json:"native"`
	ParentEventId ahp.Optional[string]                         `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                   `json:"session"`
	Synthesized   ahp.Optional[bool]                           `json:"synthesized"`
	Time          string                                       `json:"time"`
	TokenCounts   ahp.Optional[*ahp.ExecutionEventTokencounts] `json:"tokenCounts"`
	Trigger       string                                       `json:"trigger"`
	Turn          ahp.Optional[json.RawMessage]                `json:"turn"`
}

func (v ContextCompactBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Instructions.Present {
		fields["instructions"] = v.Instructions.Value
	}
	fields["items"] = v.Items
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.TokenCounts.Present {
		fields["tokenCounts"] = v.TokenCounts.Value
	}
	fields["trigger"] = v.Trigger
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type FileChangedInput struct {
	Changes       []ahp.FileChangedEventChangesItem            `json:"changes"`
	Extensions    ahp.Optional[*ahp.Extensions]                `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.FileChangedEventGapsItem] `json:"gaps"`
	ID            string                                       `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]             `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]               `json:"native"`
	ParentEventId ahp.Optional[string]                         `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                   `json:"session"`
	Synthesized   ahp.Optional[bool]                           `json:"synthesized"`
	Time          string                                       `json:"time"`
	Turn          ahp.Optional[ahp.FileChangedEventTurn]       `json:"turn"`
}

func (v FileChangedInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["changes"] = v.Changes
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type HookFailureInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]                `json:"extensions"`
	Failure       ahp.HookFailureEventFailure                  `json:"failure"`
	Gaps          ahp.Optional[[]ahp.HookFailureEventGapsItem] `json:"gaps"`
	ID            string                                       `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]             `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]               `json:"native"`
	ParentEventId string                                       `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                   `json:"session"`
	Synthesized   ahp.Optional[bool]                           `json:"synthesized"`
	Time          string                                       `json:"time"`
	Turn          ahp.Optional[ahp.HookFailureEventTurn]       `json:"turn"`
}

func (v HookFailureInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	fields["failure"] = v.Failure
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	fields["parentEventId"] = v.ParentEventId
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ModelErrorInput struct {
	Attempt       *ahp.ExecutionEventAttempt                    `json:"attempt"`
	Error         *ahp.ExecutionEventError                      `json:"error"`
	Execution     json.RawMessage                               `json:"execution"`
	Extensions    ahp.Optional[*ahp.Extensions]                 `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ModelErrorEventGapsItem]   `json:"gaps"`
	ID            string                                        `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]              `json:"items"`
	LatencyMs     ahp.Optional[json.Number]                     `json:"latencyMs"`
	Model         *ahp.ExecutionEventModel                      `json:"model"`
	Native        ahp.Optional[*ahp.NativeEvent]                `json:"native"`
	ParentEventId ahp.Optional[string]                          `json:"parentEventId"`
	Recovery      ahp.Optional[string]                          `json:"recovery"`
	Session       ahp.Optional[*ahp.Session]                    `json:"session"`
	Synthesized   ahp.Optional[bool]                            `json:"synthesized"`
	Time          string                                        `json:"time"`
	Turn          ahp.Optional[ahp.ModelErrorEventTurn]         `json:"turn"`
	Usage         ahp.Optional[*ahp.ExecutionEventAttemptusage] `json:"usage"`
}

func (v ModelErrorInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["attempt"] = v.Attempt
	fields["error"] = v.Error
	fields["execution"] = v.Execution
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.LatencyMs.Present {
		fields["latencyMs"] = v.LatencyMs.Value
	}
	fields["model"] = v.Model
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Recovery.Present {
		fields["recovery"] = v.Recovery.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	if v.Usage.Present {
		fields["usage"] = v.Usage.Value
	}
	return json.Marshal(fields)
}

type ModelRequestBeforeInput struct {
	Attempt       *ahp.ExecutionEventAttempt                          `json:"attempt"`
	Extensions    ahp.Optional[*ahp.Extensions]                       `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ModelRequestBeforeEventGapsItem] `json:"gaps"`
	ID            string                                              `json:"id"`
	Items         []*ahp.ModelVisibleItem                             `json:"items"`
	Model         *ahp.ExecutionEventModel                            `json:"model"`
	Native        ahp.Optional[*ahp.NativeEvent]                      `json:"native"`
	Params        ahp.ModelRequestBeforeEventParams                   `json:"params"`
	ParentEventId ahp.Optional[string]                                `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                          `json:"session"`
	Synthesized   ahp.Optional[bool]                                  `json:"synthesized"`
	Time          string                                              `json:"time"`
	Turn          ahp.Optional[ahp.ModelRequestBeforeEventTurn]       `json:"turn"`
}

func (v ModelRequestBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["attempt"] = v.Attempt
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	fields["items"] = v.Items
	fields["model"] = v.Model
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	fields["params"] = v.Params
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ModelResponseAfterInput struct {
	Attempt       *ahp.ExecutionEventAttempt                          `json:"attempt"`
	Execution     *ahp.ExecutionEventExecution                        `json:"execution"`
	Extensions    ahp.Optional[*ahp.Extensions]                       `json:"extensions"`
	FinishReason  string                                              `json:"finishReason"`
	Gaps          ahp.Optional[[]ahp.ModelResponseAfterEventGapsItem] `json:"gaps"`
	ID            string                                              `json:"id"`
	Items         []*ahp.ModelVisibleItem                             `json:"items"`
	LatencyMs     ahp.Optional[json.Number]                           `json:"latencyMs"`
	Model         *ahp.ExecutionEventModel                            `json:"model"`
	Native        ahp.Optional[*ahp.NativeEvent]                      `json:"native"`
	ParentEventId ahp.Optional[string]                                `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                          `json:"session"`
	Synthesized   ahp.Optional[bool]                                  `json:"synthesized"`
	Time          string                                              `json:"time"`
	Turn          ahp.Optional[ahp.ModelResponseAfterEventTurn]       `json:"turn"`
	Usage         ahp.Optional[*ahp.ExecutionEventAttemptusage]       `json:"usage"`
}

func (v ModelResponseAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["attempt"] = v.Attempt
	fields["execution"] = v.Execution
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	fields["finishReason"] = v.FinishReason
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	fields["items"] = v.Items
	if v.LatencyMs.Present {
		fields["latencyMs"] = v.LatencyMs.Value
	}
	fields["model"] = v.Model
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	if v.Usage.Present {
		fields["usage"] = v.Usage.Value
	}
	return json.Marshal(fields)
}

type ModelSwitchAfterInput struct {
	Current       *ahp.ExecutionEventModel                          `json:"current"`
	Extensions    ahp.Optional[*ahp.Extensions]                     `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ModelSwitchAfterEventGapsItem] `json:"gaps"`
	ID            string                                            `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                  `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                    `json:"native"`
	ParentEventId ahp.Optional[string]                              `json:"parentEventId"`
	Previous      *ahp.ExecutionEventModel                          `json:"previous"`
	Reason        string                                            `json:"reason"`
	Session       ahp.Optional[*ahp.Session]                        `json:"session"`
	Synthesized   ahp.Optional[bool]                                `json:"synthesized"`
	Time          string                                            `json:"time"`
	Turn          ahp.Optional[ahp.ModelSwitchAfterEventTurn]       `json:"turn"`
}

func (v ModelSwitchAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["current"] = v.Current
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["previous"] = v.Previous
	fields["reason"] = v.Reason
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ModelSwitchBeforeInput struct {
	Current       *ahp.ExecutionEventModel                           `json:"current"`
	Extensions    ahp.Optional[*ahp.Extensions]                      `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ModelSwitchBeforeEventGapsItem] `json:"gaps"`
	ID            string                                             `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                   `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                     `json:"native"`
	ParentEventId ahp.Optional[string]                               `json:"parentEventId"`
	Pricing       ahp.Optional[ahp.ModelSwitchBeforeEventPricing]    `json:"pricing"`
	Proposed      *ahp.ExecutionEventModel                           `json:"proposed"`
	Reason        string                                             `json:"reason"`
	Session       ahp.Optional[*ahp.Session]                         `json:"session"`
	Synthesized   ahp.Optional[bool]                                 `json:"synthesized"`
	Time          string                                             `json:"time"`
	Turn          ahp.Optional[ahp.ModelSwitchBeforeEventTurn]       `json:"turn"`
}

func (v ModelSwitchBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["current"] = v.Current
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Pricing.Present {
		fields["pricing"] = v.Pricing.Value
	}
	fields["proposed"] = v.Proposed
	fields["reason"] = v.Reason
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type SessionEndInput struct {
	Counters      ahp.Optional[ahp.SessionEndEventCounters]   `json:"counters"`
	Extensions    ahp.Optional[*ahp.Extensions]               `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.SessionEndEventGapsItem] `json:"gaps"`
	ID            string                                      `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]            `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]              `json:"native"`
	Outcome       ahp.SessionEndEventOutcome                  `json:"outcome"`
	ParentEventId ahp.Optional[string]                        `json:"parentEventId"`
	Reason        string                                      `json:"reason"`
	Session       *ahp.Session                                `json:"session"`
	Synthesized   ahp.Optional[bool]                          `json:"synthesized"`
	Time          string                                      `json:"time"`
	Turn          ahp.Optional[ahp.SessionEndEventTurn]       `json:"turn"`
}

func (v SessionEndInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Counters.Present {
		fields["counters"] = v.Counters.Value
	}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	fields["outcome"] = v.Outcome
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["reason"] = v.Reason
	fields["session"] = v.Session
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type SessionStartInput struct {
	Extensions     ahp.Optional[*ahp.Extensions]                  `json:"extensions"`
	Gaps           ahp.Optional[[]ahp.SessionStartEventGapsItem]  `json:"gaps"`
	Harness        ahp.SessionStartEventHarness                   `json:"harness"`
	ID             string                                         `json:"id"`
	Items          []*ahp.ModelVisibleItem                        `json:"items"`
	Native         ahp.Optional[*ahp.NativeEvent]                 `json:"native"`
	ParentEventId  ahp.Optional[string]                           `json:"parentEventId"`
	PermissionMode string                                         `json:"permissionMode"`
	ResumedFrom    ahp.Optional[ahp.SessionStartEventResumedFrom] `json:"resumedFrom"`
	Session        *ahp.Session                                   `json:"session"`
	Synthesized    ahp.Optional[bool]                             `json:"synthesized"`
	Time           string                                         `json:"time"`
	Trigger        ahp.SessionStartEventTrigger                   `json:"trigger"`
	Turn           ahp.Optional[ahp.SessionStartEventTurn]        `json:"turn"`
}

func (v SessionStartInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	fields["harness"] = v.Harness
	if v.ID != "" {
		fields["id"] = v.ID
	}
	fields["items"] = v.Items
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["permissionMode"] = v.PermissionMode
	if v.ResumedFrom.Present {
		fields["resumedFrom"] = v.ResumedFrom.Value
	}
	fields["session"] = v.Session
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["trigger"] = v.Trigger
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type TaskChangeAfterInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]                    `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.TaskChangeAfterEventGapsItem] `json:"gaps"`
	ID            string                                           `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                 `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                   `json:"native"`
	ParentEventId ahp.Optional[string]                             `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                       `json:"session"`
	Synthesized   ahp.Optional[bool]                               `json:"synthesized"`
	Task          ahp.TaskChangeAfterEventTask                     `json:"task"`
	Time          string                                           `json:"time"`
	Turn          ahp.Optional[ahp.TaskChangeAfterEventTurn]       `json:"turn"`
}

func (v TaskChangeAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	fields["task"] = v.Task
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type TaskChangeBeforeInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]                     `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.TaskChangeBeforeEventGapsItem] `json:"gaps"`
	ID            string                                            `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                  `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                    `json:"native"`
	ParentEventId ahp.Optional[string]                              `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                        `json:"session"`
	Synthesized   ahp.Optional[bool]                                `json:"synthesized"`
	Task          ahp.TaskChangeBeforeEventTask                     `json:"task"`
	Time          string                                            `json:"time"`
	Turn          ahp.Optional[ahp.TaskChangeBeforeEventTurn]       `json:"turn"`
}

func (v TaskChangeBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	fields["task"] = v.Task
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ToolAfterInput struct {
	Batch         ahp.Optional[*ahp.ExecutionEventBatch]        `json:"batch"`
	Call          ahp.ToolAfterEventCall                        `json:"call"`
	DurationMs    ahp.Optional[json.Number]                     `json:"durationMs"`
	Error         ahp.Optional[*ahp.ExecutionEventError]        `json:"error"`
	Execution     *ahp.ExecutionEventExecution                  `json:"execution"`
	Extensions    ahp.Optional[*ahp.Extensions]                 `json:"extensions"`
	FileChanges   ahp.Optional[[]*ahp.ExecutionEventFilechange] `json:"fileChanges"`
	Gaps          ahp.Optional[[]ahp.ToolAfterEventGapsItem]    `json:"gaps"`
	ID            string                                        `json:"id"`
	Items         []*ahp.ModelVisibleItem                       `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                `json:"native"`
	Outcome       ahp.ToolAfterEventOutcome                     `json:"outcome"`
	ParentEventId ahp.Optional[string]                          `json:"parentEventId"`
	Path          string                                        `json:"path"`
	Session       ahp.Optional[*ahp.Session]                    `json:"session"`
	Synthesized   ahp.Optional[bool]                            `json:"synthesized"`
	Time          string                                        `json:"time"`
	Tool          *ahp.ExecutionEventTool                       `json:"tool"`
	Turn          ahp.Optional[ahp.ToolAfterEventTurn]          `json:"turn"`
}

func (v ToolAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Batch.Present {
		fields["batch"] = v.Batch.Value
	}
	fields["call"] = v.Call
	if v.DurationMs.Present {
		fields["durationMs"] = v.DurationMs.Value
	}
	if v.Error.Present {
		fields["error"] = v.Error.Value
	}
	fields["execution"] = v.Execution
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.FileChanges.Present {
		fields["fileChanges"] = v.FileChanges.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	fields["items"] = v.Items
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	fields["outcome"] = v.Outcome
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["path"] = v.Path
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["tool"] = v.Tool
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ToolBatchAfterInput struct {
	Batch         ahp.ToolBatchAfterEventBatch                    `json:"batch"`
	Calls         []ahp.ToolBatchAfterEventCallsItem              `json:"calls"`
	Extensions    ahp.Optional[*ahp.Extensions]                   `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ToolBatchAfterEventGapsItem] `json:"gaps"`
	ID            string                                          `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                  `json:"native"`
	ParentEventId ahp.Optional[string]                            `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                      `json:"session"`
	Synthesized   ahp.Optional[bool]                              `json:"synthesized"`
	Time          string                                          `json:"time"`
	Turn          ahp.Optional[ahp.ToolBatchAfterEventTurn]       `json:"turn"`
}

func (v ToolBatchAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["batch"] = v.Batch
	fields["calls"] = v.Calls
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ToolBeforeInput[T any] struct {
	Batch         ahp.Optional[*ahp.ExecutionEventBatch]      `json:"batch"`
	Call          ahp.ToolBeforeEventCall                     `json:"call"`
	Extensions    ahp.Optional[*ahp.Extensions]               `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ToolBeforeEventGapsItem] `json:"gaps"`
	ID            string                                      `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]            `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]              `json:"native"`
	ParentEventId ahp.Optional[string]                        `json:"parentEventId"`
	Path          string                                      `json:"path"`
	Session       ahp.Optional[*ahp.Session]                  `json:"session"`
	Synthesized   ahp.Optional[bool]                          `json:"synthesized"`
	Time          string                                      `json:"time"`
	Tool          tool.Input[T]                               `json:"tool"`
	Turn          ahp.Optional[ahp.ToolBeforeEventTurn]       `json:"turn"`
}

func (v ToolBeforeInput[T]) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Batch.Present {
		fields["batch"] = v.Batch.Value
	}
	fields["call"] = v.Call
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["path"] = v.Path
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["tool"] = v.Tool
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ToolPermissionRequestInput struct {
	Batch         ahp.Optional[*ahp.ExecutionEventBatch]                 `json:"batch"`
	Call          ahp.ToolPermissionRequestEventCall                     `json:"call"`
	Extensions    ahp.Optional[*ahp.Extensions]                          `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ToolPermissionRequestEventGapsItem] `json:"gaps"`
	ID            string                                                 `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                       `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                         `json:"native"`
	ParentEventId ahp.Optional[string]                                   `json:"parentEventId"`
	Path          string                                                 `json:"path"`
	SandboxBypass bool                                                   `json:"sandboxBypass"`
	Session       ahp.Optional[*ahp.Session]                             `json:"session"`
	Suggestions   []ahp.ToolPermissionRequestEventSuggestionsItem        `json:"suggestions"`
	Synthesized   ahp.Optional[bool]                                     `json:"synthesized"`
	Time          string                                                 `json:"time"`
	Tool          *ahp.ExecutionEventTool                                `json:"tool"`
	Turn          ahp.Optional[ahp.ToolPermissionRequestEventTurn]       `json:"turn"`
}

func (v ToolPermissionRequestInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Batch.Present {
		fields["batch"] = v.Batch.Value
	}
	fields["call"] = v.Call
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["path"] = v.Path
	fields["sandboxBypass"] = v.SandboxBypass
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	fields["suggestions"] = v.Suggestions
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["tool"] = v.Tool
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ToolPermissionResolvedInput struct {
	Batch         ahp.Optional[*ahp.ExecutionEventBatch]                  `json:"batch"`
	Call          ahp.ToolPermissionResolvedEventCall                     `json:"call"`
	DecidedBy     ahp.ToolPermissionResolvedEventDecidedBy                `json:"decidedBy"`
	Decision      ahp.ToolPermissionResolvedEventDecision                 `json:"decision"`
	Extensions    ahp.Optional[*ahp.Extensions]                           `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ToolPermissionResolvedEventGapsItem] `json:"gaps"`
	ID            string                                                  `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                        `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                          `json:"native"`
	ParentEventId ahp.Optional[string]                                    `json:"parentEventId"`
	Path          string                                                  `json:"path"`
	Session       ahp.Optional[*ahp.Session]                              `json:"session"`
	Synthesized   ahp.Optional[bool]                                      `json:"synthesized"`
	Time          string                                                  `json:"time"`
	Tool          *ahp.ExecutionEventTool                                 `json:"tool"`
	Turn          ahp.Optional[ahp.ToolPermissionResolvedEventTurn]       `json:"turn"`
}

func (v ToolPermissionResolvedInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Batch.Present {
		fields["batch"] = v.Batch.Value
	}
	fields["call"] = v.Call
	fields["decidedBy"] = v.DecidedBy
	fields["decision"] = v.Decision
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["path"] = v.Path
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["tool"] = v.Tool
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type ToolProgressInput struct {
	Backgrounded  bool                                          `json:"backgrounded"`
	Batch         ahp.Optional[*ahp.ExecutionEventBatch]        `json:"batch"`
	Call          ahp.ToolProgressEventCall                     `json:"call"`
	Extensions    ahp.Optional[*ahp.Extensions]                 `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.ToolProgressEventGapsItem] `json:"gaps"`
	ID            string                                        `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]              `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                `json:"native"`
	ParentEventId ahp.Optional[string]                          `json:"parentEventId"`
	PartialOutput *ahp.ModelVisibleItem                         `json:"partialOutput"`
	Path          string                                        `json:"path"`
	Session       ahp.Optional[*ahp.Session]                    `json:"session"`
	Synthesized   ahp.Optional[bool]                            `json:"synthesized"`
	Time          string                                        `json:"time"`
	Tool          *ahp.ExecutionEventTool                       `json:"tool"`
	Turn          ahp.Optional[ahp.ToolProgressEventTurn]       `json:"turn"`
}

func (v ToolProgressInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["backgrounded"] = v.Backgrounded
	if v.Batch.Present {
		fields["batch"] = v.Batch.Value
	}
	fields["call"] = v.Call
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	fields["partialOutput"] = v.PartialOutput
	fields["path"] = v.Path
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["tool"] = v.Tool
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type TurnEndInput struct {
	ContinuationCount json.Number                                     `json:"continuationCount"`
	Error             ahp.Optional[*ahp.ExecutionEventError]          `json:"error"`
	Extensions        ahp.Optional[*ahp.Extensions]                   `json:"extensions"`
	Gaps              ahp.Optional[[]ahp.TurnEndEventGapsItem]        `json:"gaps"`
	ID                string                                          `json:"id"`
	Items             []*ahp.ModelVisibleItem                         `json:"items"`
	LastAssistantItem ahp.Optional[ahp.TurnEndEventLastAssistantItem] `json:"lastAssistantItem"`
	Native            ahp.Optional[*ahp.NativeEvent]                  `json:"native"`
	Outcome           ahp.TurnEndEventOutcome                         `json:"outcome"`
	ParentEventId     ahp.Optional[string]                            `json:"parentEventId"`
	Session           ahp.Optional[*ahp.Session]                      `json:"session"`
	Synthesized       ahp.Optional[bool]                              `json:"synthesized"`
	Time              string                                          `json:"time"`
	Turn              ahp.TurnEndEventTurn                            `json:"turn"`
	Usage             ahp.Optional[*ahp.ExecutionEventTurnusage]      `json:"usage"`
}

func (v TurnEndInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["continuationCount"] = v.ContinuationCount
	if v.Error.Present {
		fields["error"] = v.Error.Value
	}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	fields["items"] = v.Items
	if v.LastAssistantItem.Present {
		fields["lastAssistantItem"] = v.LastAssistantItem.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	fields["outcome"] = v.Outcome
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["turn"] = v.Turn
	if v.Usage.Present {
		fields["usage"] = v.Usage.Value
	}
	return json.Marshal(fields)
}

type TurnFinishBeforeInput struct {
	ContinuationCount json.Number                                              `json:"continuationCount"`
	Extensions        ahp.Optional[*ahp.Extensions]                            `json:"extensions"`
	Gaps              ahp.Optional[[]ahp.TurnFinishBeforeEventGapsItem]        `json:"gaps"`
	ID                string                                                   `json:"id"`
	Items             []*ahp.ModelVisibleItem                                  `json:"items"`
	LastAssistantItem ahp.Optional[ahp.TurnFinishBeforeEventLastAssistantItem] `json:"lastAssistantItem"`
	Native            ahp.Optional[*ahp.NativeEvent]                           `json:"native"`
	Outcome           ahp.TurnFinishBeforeEventOutcome                         `json:"outcome"`
	ParentEventId     ahp.Optional[string]                                     `json:"parentEventId"`
	Session           ahp.Optional[*ahp.Session]                               `json:"session"`
	Synthesized       ahp.Optional[bool]                                       `json:"synthesized"`
	Time              string                                                   `json:"time"`
	Turn              ahp.TurnFinishBeforeEventTurn                            `json:"turn"`
	Usage             ahp.Optional[*ahp.ExecutionEventTurnusage]               `json:"usage"`
}

func (v TurnFinishBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["continuationCount"] = v.ContinuationCount
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	fields["items"] = v.Items
	if v.LastAssistantItem.Present {
		fields["lastAssistantItem"] = v.LastAssistantItem.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	fields["outcome"] = v.Outcome
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["turn"] = v.Turn
	if v.Usage.Present {
		fields["usage"] = v.Usage.Value
	}
	return json.Marshal(fields)
}

type TurnProgressInput struct {
	Delta         *ahp.ModelVisibleItem                         `json:"delta"`
	Extensions    ahp.Optional[*ahp.Extensions]                 `json:"extensions"`
	Final         bool                                          `json:"final"`
	Gaps          ahp.Optional[[]ahp.TurnProgressEventGapsItem] `json:"gaps"`
	ID            string                                        `json:"id"`
	Item          ahp.TurnProgressEventItem                     `json:"item"`
	Items         ahp.Optional[[]*ahp.ContentItem]              `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                `json:"native"`
	ParentEventId ahp.Optional[string]                          `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                    `json:"session"`
	Synthesized   ahp.Optional[bool]                            `json:"synthesized"`
	Time          string                                        `json:"time"`
	Turn          ahp.TurnProgressEventTurn                     `json:"turn"`
}

func (v TurnProgressInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["delta"] = v.Delta
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	fields["final"] = v.Final
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	fields["item"] = v.Item
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["turn"] = v.Turn
	return json.Marshal(fields)
}

type TurnStartInput struct {
	ExpandedFrom  ahp.Optional[string]                       `json:"expandedFrom"`
	Extensions    ahp.Optional[*ahp.Extensions]              `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.TurnStartEventGapsItem] `json:"gaps"`
	ID            string                                     `json:"id"`
	Items         []*ahp.ModelVisibleItem                    `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]             `json:"native"`
	ParentEventId ahp.Optional[string]                       `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                 `json:"session"`
	Synthesized   ahp.Optional[bool]                         `json:"synthesized"`
	Time          string                                     `json:"time"`
	Trigger       ahp.TurnStartEventTrigger                  `json:"trigger"`
	Turn          ahp.TurnStartEventTurn                     `json:"turn"`
}

func (v TurnStartInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.ExpandedFrom.Present {
		fields["expandedFrom"] = v.ExpandedFrom.Value
	}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	fields["items"] = v.Items
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	fields["trigger"] = v.Trigger
	fields["turn"] = v.Turn
	return json.Marshal(fields)
}

type UserAttentionInput struct {
	Attention     ahp.UserAttentionEventAttention                `json:"attention"`
	Extensions    ahp.Optional[*ahp.Extensions]                  `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.UserAttentionEventGapsItem] `json:"gaps"`
	ID            string                                         `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]               `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                 `json:"native"`
	ParentEventId ahp.Optional[string]                           `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                     `json:"session"`
	Synthesized   ahp.Optional[bool]                             `json:"synthesized"`
	Time          string                                         `json:"time"`
	Turn          ahp.Optional[ahp.UserAttentionEventTurn]       `json:"turn"`
}

func (v UserAttentionInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["attention"] = v.Attention
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type UserElicitationRequestInput struct {
	Elicitation   ahp.UserElicitationRequestEventElicitation              `json:"elicitation"`
	Extensions    ahp.Optional[*ahp.Extensions]                           `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.UserElicitationRequestEventGapsItem] `json:"gaps"`
	ID            string                                                  `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                        `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                          `json:"native"`
	ParentEventId ahp.Optional[string]                                    `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                              `json:"session"`
	Synthesized   ahp.Optional[bool]                                      `json:"synthesized"`
	Time          string                                                  `json:"time"`
	Turn          ahp.Optional[ahp.UserElicitationRequestEventTurn]       `json:"turn"`
}

func (v UserElicitationRequestInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["elicitation"] = v.Elicitation
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type UserElicitationResultInput struct {
	Elicitation   ahp.UserElicitationResultEventElicitation              `json:"elicitation"`
	Extensions    ahp.Optional[*ahp.Extensions]                          `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.UserElicitationResultEventGapsItem] `json:"gaps"`
	ID            string                                                 `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                       `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                         `json:"native"`
	ParentEventId ahp.Optional[string]                                   `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                             `json:"session"`
	Synthesized   ahp.Optional[bool]                                     `json:"synthesized"`
	Time          string                                                 `json:"time"`
	Turn          ahp.Optional[ahp.UserElicitationResultEventTurn]       `json:"turn"`
}

func (v UserElicitationResultInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["elicitation"] = v.Elicitation
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type UserMessageInboundInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]                       `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.UserMessageInboundEventGapsItem] `json:"gaps"`
	ID            string                                              `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                    `json:"items"`
	Message       ahp.UserMessageInboundEventMessage                  `json:"message"`
	Native        ahp.Optional[*ahp.NativeEvent]                      `json:"native"`
	ParentEventId ahp.Optional[string]                                `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                          `json:"session"`
	Synthesized   ahp.Optional[bool]                                  `json:"synthesized"`
	Time          string                                              `json:"time"`
	Turn          ahp.Optional[ahp.UserMessageInboundEventTurn]       `json:"turn"`
}

func (v UserMessageInboundInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	fields["message"] = v.Message
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type UserMessageOutboundInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]                        `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.UserMessageOutboundEventGapsItem] `json:"gaps"`
	ID            string                                               `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                     `json:"items"`
	Message       ahp.UserMessageOutboundEventMessage                  `json:"message"`
	Native        ahp.Optional[*ahp.NativeEvent]                       `json:"native"`
	ParentEventId ahp.Optional[string]                                 `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                           `json:"session"`
	Synthesized   ahp.Optional[bool]                                   `json:"synthesized"`
	Time          string                                               `json:"time"`
	Turn          ahp.Optional[ahp.UserMessageOutboundEventTurn]       `json:"turn"`
}

func (v UserMessageOutboundInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	fields["message"] = v.Message
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	return json.Marshal(fields)
}

type WorkspaceChangeAfterInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]                         `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.WorkspaceChangeAfterEventGapsItem] `json:"gaps"`
	ID            string                                                `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                      `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                        `json:"native"`
	ParentEventId ahp.Optional[string]                                  `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                            `json:"session"`
	Synthesized   ahp.Optional[bool]                                    `json:"synthesized"`
	Time          string                                                `json:"time"`
	Turn          ahp.Optional[ahp.WorkspaceChangeAfterEventTurn]       `json:"turn"`
	Workspace     ahp.WorkspaceChangeAfterEventWorkspace                `json:"workspace"`
}

func (v WorkspaceChangeAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	fields["workspace"] = v.Workspace
	return json.Marshal(fields)
}

type WorkspaceChangeBeforeInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]                          `json:"extensions"`
	Gaps          ahp.Optional[[]ahp.WorkspaceChangeBeforeEventGapsItem] `json:"gaps"`
	ID            string                                                 `json:"id"`
	Items         ahp.Optional[[]*ahp.ContentItem]                       `json:"items"`
	Native        ahp.Optional[*ahp.NativeEvent]                         `json:"native"`
	ParentEventId ahp.Optional[string]                                   `json:"parentEventId"`
	Session       ahp.Optional[*ahp.Session]                             `json:"session"`
	Synthesized   ahp.Optional[bool]                                     `json:"synthesized"`
	Time          string                                                 `json:"time"`
	Turn          ahp.Optional[ahp.WorkspaceChangeBeforeEventTurn]       `json:"turn"`
	Workspace     ahp.WorkspaceChangeBeforeEventWorkspace                `json:"workspace"`
}

func (v WorkspaceChangeBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	if v.Extensions.Present {
		fields["extensions"] = v.Extensions.Value
	}
	if v.Gaps.Present {
		fields["gaps"] = v.Gaps.Value
	}
	if v.ID != "" {
		fields["id"] = v.ID
	}
	if v.Items.Present {
		fields["items"] = v.Items.Value
	}
	if v.Native.Present {
		fields["native"] = v.Native.Value
	}
	if v.ParentEventId.Present {
		fields["parentEventId"] = v.ParentEventId.Value
	}
	if v.Session.Present {
		fields["session"] = v.Session.Value
	}
	if v.Synthesized.Present {
		fields["synthesized"] = v.Synthesized.Value
	}
	if v.Time != "" {
		fields["time"] = v.Time
	}
	if v.Turn.Present {
		fields["turn"] = v.Turn.Value
	}
	fields["workspace"] = v.Workspace
	return json.Marshal(fields)
}
