// Code generated by ahp-codegen. DO NOT EDIT.
package event

import ahp "github.com/agenthooksprotocol/go-sdk"
import "encoding/json"
import "strconv"
import "github.com/agenthooksprotocol/go-sdk/content"

type Type = string
type ConfigChangeAfterInput struct {
	Change        ahp.ConfigChangeAfterEventChange
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.ConfigChangeAfterEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.ConfigChangeAfterEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ConfigChangeAfterInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ConfigChangeAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["change"] = v.Change
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ConfigChangeAfter Type = "config.change.after"

type ConfigChangeBeforeInput struct {
	Change        ahp.ConfigChangeBeforeEventChange
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.ConfigChangeBeforeEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.ConfigChangeBeforeEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ConfigChangeBeforeInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ConfigChangeBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["change"] = v.Change
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ConfigChangeBefore Type = "config.change.before"

type ContextCompactAfterInput struct {
	Execution     *ahp.ExecutionEventExecution
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.ContextCompactAfterEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ModelVisibleItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Removed       []ahp.ContextCompactAfterEventRemovedItem
	Session       ahp.Optional[*ahp.Session]
	Summary       *ahp.ModelVisibleItem
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	TokenCounts   ahp.Optional[*ahp.ExecutionEventTokencounts]
	Turn          ahp.Optional[ahp.ContextCompactAfterEventTurn]
	ItemsSources  []*content.Source `json:"-"`
	SummarySource *content.Source   `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ContextCompactAfterInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	if v.SummarySource != nil {
		sources["/summary"] = v.SummarySource
	}
	return sources
}
func (v ContextCompactAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["execution"] = v.Execution
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["removed"] = v.Removed
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		fields["summary"] = v.Summary
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.TokenCounts.Present {
			fields["tokenCounts"] = v.TokenCounts.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ContextCompactAfter Type = "context.compact.after"

type ContextCompactBeforeInput struct {
	Extensions         ahp.Optional[*ahp.Extensions]
	Gaps               ahp.Optional[[]json.RawMessage]
	ID                 ahp.Optional[string]
	Instructions       ahp.Optional[*ahp.ContentItem]
	Items              []*ahp.ModelVisibleItem
	Native             ahp.Optional[*ahp.NativeEvent]
	ParentEventID      ahp.Optional[string]
	Session            ahp.Optional[*ahp.Session]
	Synthesized        ahp.Optional[bool]
	Time               ahp.Optional[string]
	TokenCounts        ahp.Optional[*ahp.ExecutionEventTokencounts]
	Trigger            string
	Turn               ahp.Optional[json.RawMessage]
	InstructionsSource *content.Source   `json:"-"`
	ItemsSources       []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ContextCompactBeforeInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	if v.InstructionsSource != nil {
		sources["/instructions"] = v.InstructionsSource
	}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ContextCompactBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Instructions.Present {
			fields["instructions"] = v.Instructions.Value
		}
	}
	{
		fields["items"] = v.Items
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.TokenCounts.Present {
			fields["tokenCounts"] = v.TokenCounts.Value
		}
	}
	{
		fields["trigger"] = v.Trigger
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ContextCompactBefore Type = "context.compact.before"

type FileChangedInput struct {
	Changes       []ahp.FileChangedEventChangesItem
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.FileChangedEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.FileChangedEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v FileChangedInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v FileChangedInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["changes"] = v.Changes
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const FileChanged Type = "file.changed"

type HookFailureInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]
	Failure       ahp.HookFailureEventFailure
	Gaps          ahp.Optional[[]ahp.HookFailureEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID string
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.HookFailureEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v HookFailureInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v HookFailureInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		fields["failure"] = v.Failure
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		fields["parentEventId"] = v.ParentEventID
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const HookFailure Type = "hook.failure"

type ModelErrorInput struct {
	Attempt       *ahp.ExecutionEventAttempt
	Error         *ahp.ExecutionEventError
	Execution     json.RawMessage
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.ModelErrorEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	LatencyMs     ahp.Optional[json.Number]
	Model         *ahp.ExecutionEventModel
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Recovery      ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.ModelErrorEventTurn]
	Usage         ahp.Optional[*ahp.ExecutionEventAttemptusage]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ModelErrorInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ModelErrorInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["attempt"] = v.Attempt
	}
	{
		fields["error"] = v.Error
	}
	{
		fields["execution"] = v.Execution
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.LatencyMs.Present {
			fields["latencyMs"] = v.LatencyMs.Value
		}
	}
	{
		fields["model"] = v.Model
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Recovery.Present {
			fields["recovery"] = v.Recovery.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	{
		if v.Usage.Present {
			fields["usage"] = v.Usage.Value
		}
	}
	return json.Marshal(fields)
}

const ModelError Type = "model.error"

type ModelRequestBeforeInput struct {
	Attempt       *ahp.ExecutionEventAttempt
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.ModelRequestBeforeEventGapsItem]
	ID            ahp.Optional[string]
	Items         []*ahp.ModelVisibleItem
	Model         *ahp.ExecutionEventModel
	Native        ahp.Optional[*ahp.NativeEvent]
	Params        ahp.ModelRequestBeforeEventParams
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.ModelRequestBeforeEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ModelRequestBeforeInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ModelRequestBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["attempt"] = v.Attempt
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		fields["items"] = v.Items
	}
	{
		fields["model"] = v.Model
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		fields["params"] = v.Params
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ModelRequestBefore Type = "model.request.before"

type ModelResponseAfterInput struct {
	Attempt       *ahp.ExecutionEventAttempt
	Execution     *ahp.ExecutionEventExecution
	Extensions    ahp.Optional[*ahp.Extensions]
	FinishReason  string
	Gaps          ahp.Optional[[]ahp.ModelResponseAfterEventGapsItem]
	ID            ahp.Optional[string]
	Items         []*ahp.ModelVisibleItem
	LatencyMs     ahp.Optional[json.Number]
	Model         *ahp.ExecutionEventModel
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.ModelResponseAfterEventTurn]
	Usage         ahp.Optional[*ahp.ExecutionEventAttemptusage]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ModelResponseAfterInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ModelResponseAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["attempt"] = v.Attempt
	}
	{
		fields["execution"] = v.Execution
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		fields["finishReason"] = v.FinishReason
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		fields["items"] = v.Items
	}
	{
		if v.LatencyMs.Present {
			fields["latencyMs"] = v.LatencyMs.Value
		}
	}
	{
		fields["model"] = v.Model
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	{
		if v.Usage.Present {
			fields["usage"] = v.Usage.Value
		}
	}
	return json.Marshal(fields)
}

const ModelResponseAfter Type = "model.response.after"

type ModelSwitchAfterInput struct {
	Current       *ahp.ExecutionEventModel
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.ModelSwitchAfterEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Previous      *ahp.ExecutionEventModel
	Reason        string
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.ModelSwitchAfterEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ModelSwitchAfterInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ModelSwitchAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["current"] = v.Current
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["previous"] = v.Previous
	}
	{
		fields["reason"] = v.Reason
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ModelSwitchAfter Type = "model.switch.after"

type ModelSwitchBeforeInput struct {
	Current       *ahp.ExecutionEventModel
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.ModelSwitchBeforeEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Pricing       ahp.Optional[ahp.ModelSwitchBeforeEventPricing]
	Proposed      *ahp.ExecutionEventModel
	Reason        string
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.ModelSwitchBeforeEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ModelSwitchBeforeInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ModelSwitchBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["current"] = v.Current
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Pricing.Present {
			fields["pricing"] = v.Pricing.Value
		}
	}
	{
		fields["proposed"] = v.Proposed
	}
	{
		fields["reason"] = v.Reason
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ModelSwitchBefore Type = "model.switch.before"

type SessionEndInput struct {
	Counters      ahp.Optional[ahp.SessionEndEventCounters]
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.SessionEndEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	Outcome       ahp.SessionEndEventOutcome
	ParentEventID ahp.Optional[string]
	Reason        string
	Session       *ahp.Session
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.SessionEndEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v SessionEndInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v SessionEndInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Counters.Present {
			fields["counters"] = v.Counters.Value
		}
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		fields["outcome"] = v.Outcome
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["reason"] = v.Reason
	}
	{
		fields["session"] = v.Session
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const SessionEnd Type = "session.end"

type SessionStartInput struct {
	Extensions     ahp.Optional[*ahp.Extensions]
	Gaps           ahp.Optional[[]ahp.SessionStartEventGapsItem]
	Harness        ahp.SessionStartEventHarness
	ID             ahp.Optional[string]
	Items          []*ahp.ModelVisibleItem
	Native         ahp.Optional[*ahp.NativeEvent]
	ParentEventID  ahp.Optional[string]
	PermissionMode string
	ResumedFrom    ahp.Optional[ahp.SessionStartEventResumedFrom]
	Session        *ahp.Session
	Synthesized    ahp.Optional[bool]
	Time           ahp.Optional[string]
	Trigger        ahp.SessionStartEventTrigger
	Turn           ahp.Optional[ahp.SessionStartEventTurn]
	ItemsSources   []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v SessionStartInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v SessionStartInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		fields["harness"] = v.Harness
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		fields["items"] = v.Items
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["permissionMode"] = v.PermissionMode
	}
	{
		if v.ResumedFrom.Present {
			fields["resumedFrom"] = v.ResumedFrom.Value
		}
	}
	{
		fields["session"] = v.Session
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		fields["trigger"] = v.Trigger
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const SessionStart Type = "session.start"

type TaskChangeAfterInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.TaskChangeAfterEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Task          ahp.TaskChangeAfterEventTask
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.TaskChangeAfterEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v TaskChangeAfterInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v TaskChangeAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		fields["task"] = v.Task
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const TaskChangeAfter Type = "task.change.after"

type TaskChangeBeforeInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.TaskChangeBeforeEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Task          ahp.TaskChangeBeforeEventTask
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.TaskChangeBeforeEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v TaskChangeBeforeInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v TaskChangeBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		fields["task"] = v.Task
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const TaskChangeBefore Type = "task.change.before"

type ToolAfterInput struct {
	Batch                    ahp.Optional[*ahp.ExecutionEventBatch]
	CallID                   string
	CallSynthesized          ahp.Optional[bool]
	DurationMs               ahp.Optional[json.Number]
	Error                    ahp.Optional[*ahp.ExecutionEventError]
	Execution                *ahp.ExecutionEventExecution
	Extensions               ahp.Optional[*ahp.Extensions]
	FileChanges              ahp.Optional[[]*ahp.ExecutionEventFilechange]
	Gaps                     ahp.Optional[[]ahp.ToolAfterEventGapsItem]
	ID                       ahp.Optional[string]
	Items                    []*ahp.ModelVisibleItem
	Native                   ahp.Optional[*ahp.NativeEvent]
	Outcome                  ahp.ToolAfterEventOutcome
	ParentEventID            ahp.Optional[string]
	Path                     string
	Session                  ahp.Optional[*ahp.Session]
	Synthesized              ahp.Optional[bool]
	Time                     ahp.Optional[string]
	Input                    ahp.ExecutionEventToolInput
	ToolKind                 ahp.Optional[string]
	ToolMcp                  ahp.Optional[*ahp.ExecutionEventMcp]
	Name                     string
	Origin                   ahp.ExecutionEventToolOrigin
	Turn                     ahp.Optional[ahp.ToolAfterEventTurn]
	FileChangesAfterSources  []*content.Source `json:"-"`
	FileChangesBeforeSources []*content.Source `json:"-"`
	ItemsSources             []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ToolAfterInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.FileChangesAfterSources {
		if source != nil {
			sources["/fileChanges/"+strconv.Itoa(index)+"/after"] = source
		}
	}
	for index, source := range v.FileChangesBeforeSources {
		if source != nil {
			sources["/fileChanges/"+strconv.Itoa(index)+"/before"] = source
		}
	}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ToolAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Batch.Present {
			fields["batch"] = v.Batch.Value
		}
	}
	{
		nested0, ok := fields["call"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["call"] = nested0
		}
		nested0["id"] = v.CallID
	}
	{
		if v.CallSynthesized.Present {
			nested0, ok := fields["call"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["call"] = nested0
			}
			nested0["synthesized"] = v.CallSynthesized.Value
		}
	}
	{
		if v.DurationMs.Present {
			fields["durationMs"] = v.DurationMs.Value
		}
	}
	{
		if v.Error.Present {
			fields["error"] = v.Error.Value
		}
	}
	{
		fields["execution"] = v.Execution
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.FileChanges.Present {
			fields["fileChanges"] = v.FileChanges.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		fields["items"] = v.Items
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		fields["outcome"] = v.Outcome
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["path"] = v.Path
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["input"] = v.Input
	}
	{
		if v.ToolKind.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["kind"] = v.ToolKind.Value
		}
	}
	{
		if v.ToolMcp.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["mcp"] = v.ToolMcp.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["name"] = v.Name
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["origin"] = v.Origin
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ToolAfter Type = "tool.after"

type ToolBatchAfterInput struct {
	Batch         ahp.ToolBatchAfterEventBatch
	Calls         []ahp.ToolBatchAfterEventCallsItem
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.ToolBatchAfterEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.ToolBatchAfterEventTurn]
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ToolBatchAfterInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ToolBatchAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["batch"] = v.Batch
	}
	{
		fields["calls"] = v.Calls
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ToolBatchAfter Type = "tool.batch.after"

type ToolBeforeInput[T any] struct {
	Batch           ahp.Optional[*ahp.ExecutionEventBatch]
	CallID          string
	CallSynthesized ahp.Optional[bool]
	Extensions      ahp.Optional[*ahp.Extensions]
	Gaps            ahp.Optional[[]ahp.ToolBeforeEventGapsItem]
	ID              ahp.Optional[string]
	Items           ahp.Optional[[]*ahp.ContentItem]
	Native          ahp.Optional[*ahp.NativeEvent]
	ParentEventID   ahp.Optional[string]
	Path            string
	Session         ahp.Optional[*ahp.Session]
	Synthesized     ahp.Optional[bool]
	Time            ahp.Optional[string]
	Input           T
	ToolKind        ahp.Optional[string]
	ToolMcp         ahp.Optional[*ahp.ExecutionEventMcp]
	Name            string
	Origin          ahp.ExecutionEventToolOrigin
	Turn            ahp.Optional[ahp.ToolBeforeEventTurn]
	ItemsSources    []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ToolBeforeInput[T]) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ToolBeforeInput[T]) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Batch.Present {
			fields["batch"] = v.Batch.Value
		}
	}
	{
		nested0, ok := fields["call"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["call"] = nested0
		}
		nested0["id"] = v.CallID
	}
	{
		if v.CallSynthesized.Present {
			nested0, ok := fields["call"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["call"] = nested0
			}
			nested0["synthesized"] = v.CallSynthesized.Value
		}
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["path"] = v.Path
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["input"] = v.Input
	}
	{
		if v.ToolKind.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["kind"] = v.ToolKind.Value
		}
	}
	{
		if v.ToolMcp.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["mcp"] = v.ToolMcp.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["name"] = v.Name
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["origin"] = v.Origin
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ToolBefore Type = "tool.before"

type ToolPermissionRequestInput struct {
	Batch           ahp.Optional[*ahp.ExecutionEventBatch]
	CallID          string
	CallSynthesized ahp.Optional[bool]
	Extensions      ahp.Optional[*ahp.Extensions]
	Gaps            ahp.Optional[[]ahp.ToolPermissionRequestEventGapsItem]
	ID              ahp.Optional[string]
	Items           ahp.Optional[[]*ahp.ContentItem]
	Native          ahp.Optional[*ahp.NativeEvent]
	ParentEventID   ahp.Optional[string]
	Path            string
	SandboxBypass   bool
	Session         ahp.Optional[*ahp.Session]
	Suggestions     []ahp.ToolPermissionRequestEventSuggestionsItem
	Synthesized     ahp.Optional[bool]
	Time            ahp.Optional[string]
	Input           ahp.ExecutionEventToolInput
	ToolKind        ahp.Optional[string]
	ToolMcp         ahp.Optional[*ahp.ExecutionEventMcp]
	Name            string
	Origin          ahp.ExecutionEventToolOrigin
	Turn            ahp.Optional[ahp.ToolPermissionRequestEventTurn]
	ItemsSources    []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ToolPermissionRequestInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ToolPermissionRequestInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Batch.Present {
			fields["batch"] = v.Batch.Value
		}
	}
	{
		nested0, ok := fields["call"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["call"] = nested0
		}
		nested0["id"] = v.CallID
	}
	{
		if v.CallSynthesized.Present {
			nested0, ok := fields["call"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["call"] = nested0
			}
			nested0["synthesized"] = v.CallSynthesized.Value
		}
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["path"] = v.Path
	}
	{
		fields["sandboxBypass"] = v.SandboxBypass
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		fields["suggestions"] = v.Suggestions
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["input"] = v.Input
	}
	{
		if v.ToolKind.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["kind"] = v.ToolKind.Value
		}
	}
	{
		if v.ToolMcp.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["mcp"] = v.ToolMcp.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["name"] = v.Name
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["origin"] = v.Origin
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ToolPermissionRequest Type = "tool.permission.request"

type ToolPermissionResolvedInput struct {
	Batch           ahp.Optional[*ahp.ExecutionEventBatch]
	CallID          string
	CallSynthesized ahp.Optional[bool]
	DecidedBy       ahp.ToolPermissionResolvedEventDecidedBy
	Decision        ahp.ToolPermissionResolvedEventDecision
	Extensions      ahp.Optional[*ahp.Extensions]
	Gaps            ahp.Optional[[]ahp.ToolPermissionResolvedEventGapsItem]
	ID              ahp.Optional[string]
	Items           ahp.Optional[[]*ahp.ContentItem]
	Native          ahp.Optional[*ahp.NativeEvent]
	ParentEventID   ahp.Optional[string]
	Path            string
	Session         ahp.Optional[*ahp.Session]
	Synthesized     ahp.Optional[bool]
	Time            ahp.Optional[string]
	Input           ahp.ExecutionEventToolInput
	ToolKind        ahp.Optional[string]
	ToolMcp         ahp.Optional[*ahp.ExecutionEventMcp]
	Name            string
	Origin          ahp.ExecutionEventToolOrigin
	Turn            ahp.Optional[ahp.ToolPermissionResolvedEventTurn]
	ItemsSources    []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ToolPermissionResolvedInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v ToolPermissionResolvedInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Batch.Present {
			fields["batch"] = v.Batch.Value
		}
	}
	{
		nested0, ok := fields["call"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["call"] = nested0
		}
		nested0["id"] = v.CallID
	}
	{
		if v.CallSynthesized.Present {
			nested0, ok := fields["call"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["call"] = nested0
			}
			nested0["synthesized"] = v.CallSynthesized.Value
		}
	}
	{
		fields["decidedBy"] = v.DecidedBy
	}
	{
		fields["decision"] = v.Decision
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["path"] = v.Path
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["input"] = v.Input
	}
	{
		if v.ToolKind.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["kind"] = v.ToolKind.Value
		}
	}
	{
		if v.ToolMcp.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["mcp"] = v.ToolMcp.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["name"] = v.Name
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["origin"] = v.Origin
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ToolPermissionResolved Type = "tool.permission.resolved"

type ToolProgressInput struct {
	Backgrounded        bool
	Batch               ahp.Optional[*ahp.ExecutionEventBatch]
	CallID              string
	CallSynthesized     ahp.Optional[bool]
	Extensions          ahp.Optional[*ahp.Extensions]
	Gaps                ahp.Optional[[]ahp.ToolProgressEventGapsItem]
	ID                  ahp.Optional[string]
	Items               ahp.Optional[[]*ahp.ContentItem]
	Native              ahp.Optional[*ahp.NativeEvent]
	ParentEventID       ahp.Optional[string]
	PartialOutput       *ahp.ModelVisibleItem
	Path                string
	Session             ahp.Optional[*ahp.Session]
	Synthesized         ahp.Optional[bool]
	Time                ahp.Optional[string]
	Input               ahp.ExecutionEventToolInput
	ToolKind            ahp.Optional[string]
	ToolMcp             ahp.Optional[*ahp.ExecutionEventMcp]
	Name                string
	Origin              ahp.ExecutionEventToolOrigin
	Turn                ahp.Optional[ahp.ToolProgressEventTurn]
	ItemsSources        []*content.Source `json:"-"`
	PartialOutputSource *content.Source   `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v ToolProgressInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	if v.PartialOutputSource != nil {
		sources["/partialOutput"] = v.PartialOutputSource
	}
	return sources
}
func (v ToolProgressInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["backgrounded"] = v.Backgrounded
	}
	{
		if v.Batch.Present {
			fields["batch"] = v.Batch.Value
		}
	}
	{
		nested0, ok := fields["call"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["call"] = nested0
		}
		nested0["id"] = v.CallID
	}
	{
		if v.CallSynthesized.Present {
			nested0, ok := fields["call"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["call"] = nested0
			}
			nested0["synthesized"] = v.CallSynthesized.Value
		}
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		fields["partialOutput"] = v.PartialOutput
	}
	{
		fields["path"] = v.Path
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["input"] = v.Input
	}
	{
		if v.ToolKind.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["kind"] = v.ToolKind.Value
		}
	}
	{
		if v.ToolMcp.Present {
			nested0, ok := fields["tool"].(map[string]any)
			if !ok {
				nested0 = map[string]any{}
				fields["tool"] = nested0
			}
			nested0["mcp"] = v.ToolMcp.Value
		}
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["name"] = v.Name
	}
	{
		nested0, ok := fields["tool"].(map[string]any)
		if !ok {
			nested0 = map[string]any{}
			fields["tool"] = nested0
		}
		nested0["origin"] = v.Origin
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const ToolProgress Type = "tool.progress"

type TurnEndInput struct {
	ContinuationCount json.Number
	Error             ahp.Optional[*ahp.ExecutionEventError]
	Extensions        ahp.Optional[*ahp.Extensions]
	Gaps              ahp.Optional[[]ahp.TurnEndEventGapsItem]
	ID                ahp.Optional[string]
	Items             []*ahp.ModelVisibleItem
	LastAssistantItem ahp.Optional[ahp.TurnEndEventLastAssistantItem]
	Native            ahp.Optional[*ahp.NativeEvent]
	Outcome           ahp.TurnEndEventOutcome
	ParentEventID     ahp.Optional[string]
	Session           ahp.Optional[*ahp.Session]
	Synthesized       ahp.Optional[bool]
	Time              ahp.Optional[string]
	Turn              ahp.TurnEndEventTurn
	Usage             ahp.Optional[*ahp.ExecutionEventTurnusage]
	ItemsSources      []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v TurnEndInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v TurnEndInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["continuationCount"] = v.ContinuationCount
	}
	{
		if v.Error.Present {
			fields["error"] = v.Error.Value
		}
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		fields["items"] = v.Items
	}
	{
		if v.LastAssistantItem.Present {
			fields["lastAssistantItem"] = v.LastAssistantItem.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		fields["outcome"] = v.Outcome
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		fields["turn"] = v.Turn
	}
	{
		if v.Usage.Present {
			fields["usage"] = v.Usage.Value
		}
	}
	return json.Marshal(fields)
}

const TurnEnd Type = "turn.end"

type TurnFinishBeforeInput struct {
	ContinuationCount json.Number
	Extensions        ahp.Optional[*ahp.Extensions]
	Gaps              ahp.Optional[[]ahp.TurnFinishBeforeEventGapsItem]
	ID                ahp.Optional[string]
	Items             []*ahp.ModelVisibleItem
	LastAssistantItem ahp.Optional[ahp.TurnFinishBeforeEventLastAssistantItem]
	Native            ahp.Optional[*ahp.NativeEvent]
	Outcome           ahp.TurnFinishBeforeEventOutcome
	ParentEventID     ahp.Optional[string]
	Session           ahp.Optional[*ahp.Session]
	Synthesized       ahp.Optional[bool]
	Time              ahp.Optional[string]
	Turn              ahp.TurnFinishBeforeEventTurn
	Usage             ahp.Optional[*ahp.ExecutionEventTurnusage]
	ItemsSources      []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v TurnFinishBeforeInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v TurnFinishBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["continuationCount"] = v.ContinuationCount
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		fields["items"] = v.Items
	}
	{
		if v.LastAssistantItem.Present {
			fields["lastAssistantItem"] = v.LastAssistantItem.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		fields["outcome"] = v.Outcome
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		fields["turn"] = v.Turn
	}
	{
		if v.Usage.Present {
			fields["usage"] = v.Usage.Value
		}
	}
	return json.Marshal(fields)
}

const TurnFinishBefore Type = "turn.finish.before"

type TurnProgressInput struct {
	Delta         *ahp.ModelVisibleItem
	Extensions    ahp.Optional[*ahp.Extensions]
	Final         bool
	Gaps          ahp.Optional[[]ahp.TurnProgressEventGapsItem]
	ID            ahp.Optional[string]
	Item          ahp.TurnProgressEventItem
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.TurnProgressEventTurn
	DeltaSource   *content.Source   `json:"-"`
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v TurnProgressInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	if v.DeltaSource != nil {
		sources["/delta"] = v.DeltaSource
	}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v TurnProgressInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["delta"] = v.Delta
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		fields["final"] = v.Final
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		fields["item"] = v.Item
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		fields["turn"] = v.Turn
	}
	return json.Marshal(fields)
}

const TurnProgress Type = "turn.progress"

type TurnStartInput struct {
	ExpandedFrom  ahp.Optional[string]
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.TurnStartEventGapsItem]
	ID            ahp.Optional[string]
	Items         []*ahp.ModelVisibleItem
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Trigger       ahp.TurnStartEventTrigger
	Turn          ahp.TurnStartEventTurn
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v TurnStartInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v TurnStartInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.ExpandedFrom.Present {
			fields["expandedFrom"] = v.ExpandedFrom.Value
		}
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		fields["items"] = v.Items
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		fields["trigger"] = v.Trigger
	}
	{
		fields["turn"] = v.Turn
	}
	return json.Marshal(fields)
}

const TurnStart Type = "turn.start"

type UserAttentionInput struct {
	Attention               ahp.UserAttentionEventAttention
	Extensions              ahp.Optional[*ahp.Extensions]
	Gaps                    ahp.Optional[[]ahp.UserAttentionEventGapsItem]
	ID                      ahp.Optional[string]
	Items                   ahp.Optional[[]*ahp.ContentItem]
	Native                  ahp.Optional[*ahp.NativeEvent]
	ParentEventID           ahp.Optional[string]
	Session                 ahp.Optional[*ahp.Session]
	Synthesized             ahp.Optional[bool]
	Time                    ahp.Optional[string]
	Turn                    ahp.Optional[ahp.UserAttentionEventTurn]
	AttentionMessageSources []*content.Source `json:"-"`
	AttentionTitleSources   []*content.Source `json:"-"`
	ItemsSources            []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v UserAttentionInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.AttentionMessageSources {
		if source != nil {
			sources["/attention/message/"+strconv.Itoa(index)+""] = source
		}
	}
	for index, source := range v.AttentionTitleSources {
		if source != nil {
			sources["/attention/title/"+strconv.Itoa(index)+""] = source
		}
	}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v UserAttentionInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["attention"] = v.Attention
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const UserAttention Type = "user.attention"

type UserElicitationRequestInput struct {
	Elicitation              ahp.UserElicitationRequestEventElicitation
	Extensions               ahp.Optional[*ahp.Extensions]
	Gaps                     ahp.Optional[[]ahp.UserElicitationRequestEventGapsItem]
	ID                       ahp.Optional[string]
	Items                    ahp.Optional[[]*ahp.ContentItem]
	Native                   ahp.Optional[*ahp.NativeEvent]
	ParentEventID            ahp.Optional[string]
	Session                  ahp.Optional[*ahp.Session]
	Synthesized              ahp.Optional[bool]
	Time                     ahp.Optional[string]
	Turn                     ahp.Optional[ahp.UserElicitationRequestEventTurn]
	ElicitationRequestSource *content.Source   `json:"-"`
	ItemsSources             []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v UserElicitationRequestInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	if v.ElicitationRequestSource != nil {
		sources["/elicitation/request"] = v.ElicitationRequestSource
	}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v UserElicitationRequestInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["elicitation"] = v.Elicitation
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const UserElicitationRequest Type = "user.elicitation.request"

type UserElicitationResultInput struct {
	Elicitation             ahp.UserElicitationResultEventElicitation
	Extensions              ahp.Optional[*ahp.Extensions]
	Gaps                    ahp.Optional[[]ahp.UserElicitationResultEventGapsItem]
	ID                      ahp.Optional[string]
	Items                   ahp.Optional[[]*ahp.ContentItem]
	Native                  ahp.Optional[*ahp.NativeEvent]
	ParentEventID           ahp.Optional[string]
	Session                 ahp.Optional[*ahp.Session]
	Synthesized             ahp.Optional[bool]
	Time                    ahp.Optional[string]
	Turn                    ahp.Optional[ahp.UserElicitationResultEventTurn]
	ElicitationResultSource *content.Source   `json:"-"`
	ItemsSources            []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v UserElicitationResultInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	if v.ElicitationResultSource != nil {
		sources["/elicitation/result"] = v.ElicitationResultSource
	}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v UserElicitationResultInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		fields["elicitation"] = v.Elicitation
	}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const UserElicitationResult Type = "user.elicitation.result"

type UserMessageInboundInput struct {
	Extensions         ahp.Optional[*ahp.Extensions]
	Gaps               ahp.Optional[[]ahp.UserMessageInboundEventGapsItem]
	ID                 ahp.Optional[string]
	Items              ahp.Optional[[]*ahp.ContentItem]
	Message            ahp.UserMessageInboundEventMessage
	Native             ahp.Optional[*ahp.NativeEvent]
	ParentEventID      ahp.Optional[string]
	Session            ahp.Optional[*ahp.Session]
	Synthesized        ahp.Optional[bool]
	Time               ahp.Optional[string]
	Turn               ahp.Optional[ahp.UserMessageInboundEventTurn]
	ItemsSources       []*content.Source `json:"-"`
	MessageTextSources []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v UserMessageInboundInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	for index, source := range v.MessageTextSources {
		if source != nil {
			sources["/message/text/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v UserMessageInboundInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		fields["message"] = v.Message
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const UserMessageInbound Type = "user.message.inbound"

type UserMessageOutboundInput struct {
	Extensions            ahp.Optional[*ahp.Extensions]
	Gaps                  ahp.Optional[[]ahp.UserMessageOutboundEventGapsItem]
	ID                    ahp.Optional[string]
	Items                 ahp.Optional[[]*ahp.ContentItem]
	Message               ahp.UserMessageOutboundEventMessage
	Native                ahp.Optional[*ahp.NativeEvent]
	ParentEventID         ahp.Optional[string]
	Session               ahp.Optional[*ahp.Session]
	Synthesized           ahp.Optional[bool]
	Time                  ahp.Optional[string]
	Turn                  ahp.Optional[ahp.UserMessageOutboundEventTurn]
	ItemsSources          []*content.Source `json:"-"`
	MessagePayloadSources []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v UserMessageOutboundInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	for index, source := range v.MessagePayloadSources {
		if source != nil {
			sources["/message/payload/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v UserMessageOutboundInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		fields["message"] = v.Message
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	return json.Marshal(fields)
}

const UserMessageOutbound Type = "user.message.outbound"

type WorkspaceChangeAfterInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.WorkspaceChangeAfterEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.WorkspaceChangeAfterEventTurn]
	Workspace     ahp.WorkspaceChangeAfterEventWorkspace
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v WorkspaceChangeAfterInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v WorkspaceChangeAfterInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	{
		fields["workspace"] = v.Workspace
	}
	return json.Marshal(fields)
}

const WorkspaceChangeAfter Type = "workspace.change.after"

type WorkspaceChangeBeforeInput struct {
	Extensions    ahp.Optional[*ahp.Extensions]
	Gaps          ahp.Optional[[]ahp.WorkspaceChangeBeforeEventGapsItem]
	ID            ahp.Optional[string]
	Items         ahp.Optional[[]*ahp.ContentItem]
	Native        ahp.Optional[*ahp.NativeEvent]
	ParentEventID ahp.Optional[string]
	Session       ahp.Optional[*ahp.Session]
	Synthesized   ahp.Optional[bool]
	Time          ahp.Optional[string]
	Turn          ahp.Optional[ahp.WorkspaceChangeBeforeEventTurn]
	Workspace     ahp.WorkspaceChangeBeforeEventWorkspace
	ItemsSources  []*content.Source `json:"-"`
}

// AHPContentSources returns owned sources out of band; descriptors stay in canonical JSON.
func (v WorkspaceChangeBeforeInput) AHPContentSources() map[string]*content.Source {
	sources := map[string]*content.Source{}
	for index, source := range v.ItemsSources {
		if source != nil {
			sources["/items/"+strconv.Itoa(index)+""] = source
		}
	}
	return sources
}
func (v WorkspaceChangeBeforeInput) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	{
		if v.Extensions.Present {
			fields["extensions"] = v.Extensions.Value
		}
	}
	{
		if v.Gaps.Present {
			fields["gaps"] = v.Gaps.Value
		}
	}
	{
		if v.ID.Present {
			fields["id"] = v.ID.Value
		}
	}
	{
		if v.Items.Present {
			fields["items"] = v.Items.Value
		}
	}
	{
		if v.Native.Present {
			fields["native"] = v.Native.Value
		}
	}
	{
		if v.ParentEventID.Present {
			fields["parentEventId"] = v.ParentEventID.Value
		}
	}
	{
		if v.Session.Present {
			fields["session"] = v.Session.Value
		}
	}
	{
		if v.Synthesized.Present {
			fields["synthesized"] = v.Synthesized.Value
		}
	}
	{
		if v.Time.Present {
			fields["time"] = v.Time.Value
		}
	}
	{
		if v.Turn.Present {
			fields["turn"] = v.Turn.Value
		}
	}
	{
		fields["workspace"] = v.Workspace
	}
	return json.Marshal(fields)
}

const WorkspaceChangeBefore Type = "workspace.change.before"
