// Code generated by ahp-codegen. DO NOT EDIT.
package effect

import ahp "github.com/agenthooksprotocol/go-sdk"
import "encoding/json"

type DenyOption func(*ahp.DenyEffect)

func WithDenyCode(value string) DenyOption {
	return func(v *ahp.DenyEffect) { v.Code = ahp.Optional[string]{Present: true, Value: value} }
}
func WithDenyExtensions(value *ahp.Extensions) DenyOption {
	return func(v *ahp.DenyEffect) { v.Extensions = ahp.Optional[*ahp.Extensions]{Present: true, Value: value} }
}
func NewDeny(argReason string, opts ...DenyOption) *ahp.Effect {
	v := &ahp.DenyEffect{Reason: argReason, Type: "deny"}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{DenyEffect: ahp.Optional[*ahp.DenyEffect]{Present: true, Value: v}}
}

type AllowOption func(*ahp.EffectVariant2)

func NewAllow(opts ...AllowOption) *ahp.Effect {
	v := &ahp.EffectVariant2{Type: "allow"}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{Variant2: ahp.Optional[ahp.EffectVariant2]{Present: true, Value: *v}}
}

type AskOption func(*ahp.EffectVariant3)

func NewAsk(opts ...AskOption) *ahp.Effect {
	v := &ahp.EffectVariant3{Type: "ask"}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{Variant3: ahp.Optional[ahp.EffectVariant3]{Present: true, Value: *v}}
}

type ModifyOption func(*ahp.EffectVariant4)

func NewModify(argOperation ahp.EffectVariant4Operation, argTarget ahp.EffectVariant4Target, argValue json.RawMessage, opts ...ModifyOption) *ahp.Effect {
	v := &ahp.EffectVariant4{Operation: argOperation, Target: argTarget, Type: "modify", Value: argValue}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{Variant4: ahp.Optional[ahp.EffectVariant4]{Present: true, Value: *v}}
}

type MessageOption func(*ahp.EffectVariant5)

func NewMessage(argText string, opts ...MessageOption) *ahp.Effect {
	v := &ahp.EffectVariant5{Text: argText, Type: "message"}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{Variant5: ahp.Optional[ahp.EffectVariant5]{Present: true, Value: *v}}
}

type ReturnOption func(*ahp.EffectVariant6)

func NewReturn(argValue json.RawMessage, opts ...ReturnOption) *ahp.Effect {
	v := &ahp.EffectVariant6{Type: "return", Value: argValue}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{Variant6: ahp.Optional[ahp.EffectVariant6]{Present: true, Value: *v}}
}

type FlowStopOption func(*ahp.EffectVariant7)

func NewFlowStop(argReason string, opts ...FlowStopOption) *ahp.Effect {
	v := &ahp.EffectVariant7{Operation: "stop", Reason: argReason, Type: "flow"}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{Variant7: ahp.Optional[ahp.EffectVariant7]{Present: true, Value: *v}}
}

type FlowContinueOption func(*ahp.EffectVariant8)

func WithFlowContinueInstruction(value string) FlowContinueOption {
	return func(v *ahp.EffectVariant8) { v.Instruction = ahp.Optional[string]{Present: true, Value: value} }
}
func NewFlowContinue(opts ...FlowContinueOption) *ahp.Effect {
	v := &ahp.EffectVariant8{Operation: "continue", Type: "flow"}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{Variant8: ahp.Optional[ahp.EffectVariant8]{Present: true, Value: *v}}
}

type InjectAppendOption func(*ahp.EffectVariant9)

func NewInjectAppend(argDeliverAt ahp.EffectVariant9DeliverAt, argValue json.RawMessage, opts ...InjectAppendOption) *ahp.Effect {
	v := &ahp.EffectVariant9{DeliverAt: argDeliverAt, Operation: "append", Target: "context", Type: "inject", Value: argValue}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return &ahp.Effect{Variant9: ahp.Optional[ahp.EffectVariant9]{Present: true, Value: *v}}
}
