// Code generated by ahp-codegen. DO NOT EDIT.
package content

import ahp "github.com/agenthooksprotocol/go-sdk"
import "encoding/json"
import "time"
import "fmt"
import "strconv"
import "strings"

type ReferenceOption func(*ahp.ContentReference)

func NewReference(argRef string, argSha256 string, argSize json.Number, opts ...ReferenceOption) *ahp.ContentReference {
	v := &ahp.ContentReference{Ref: argRef, Sha256: argSha256, Size: argSize}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type SelectionOption func(*ahp.ContentSelection)

func WithSelectionAudio(value ahp.ContentSelectionAudio) SelectionOption {
	return func(v *ahp.ContentSelection) {
		v.Audio = ahp.Optional[ahp.ContentSelectionAudio]{Present: true, Value: value}
	}
}
func WithSelectionFiles(value ahp.ContentSelectionFiles) SelectionOption {
	return func(v *ahp.ContentSelection) {
		v.Files = ahp.Optional[ahp.ContentSelectionFiles]{Present: true, Value: value}
	}
}
func WithSelectionImages(value ahp.ContentSelectionImages) SelectionOption {
	return func(v *ahp.ContentSelection) {
		v.Images = ahp.Optional[ahp.ContentSelectionImages]{Present: true, Value: value}
	}
}
func WithSelectionReasoning(value ahp.ContentSelectionReasoning) SelectionOption {
	return func(v *ahp.ContentSelection) {
		v.Reasoning = ahp.Optional[ahp.ContentSelectionReasoning]{Present: true, Value: value}
	}
}
func WithSelectionText(value ahp.ContentSelectionText) SelectionOption {
	return func(v *ahp.ContentSelection) {
		v.Text = ahp.Optional[ahp.ContentSelectionText]{Present: true, Value: value}
	}
}
func WithSelectionVideo(value ahp.ContentSelectionVideo) SelectionOption {
	return func(v *ahp.ContentSelection) {
		v.Video = ahp.Optional[ahp.ContentSelectionVideo]{Present: true, Value: value}
	}
}
func NewSelection(argDefault ahp.ContentSelectionDefault, opts ...SelectionOption) *ahp.ContentSelection {
	v := &ahp.ContentSelection{Default: argDefault}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type UploadOption func(*ahp.ContentUpload)

func WithUploadAuth(value *ahp.Authentication) UploadOption {
	return func(v *ahp.ContentUpload) { v.Auth = ahp.Optional[*ahp.Authentication]{Present: true, Value: value} }
}
func NewUploadMilliseconds(argEndpoint string, argMaxBytes json.Number, argTimeoutMs json.Number, opts ...UploadOption) *ahp.ContentUpload {
	v := &ahp.ContentUpload{Endpoint: argEndpoint, MaxBytes: argMaxBytes, TimeoutMs: argTimeoutMs}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

// NewUpload constructs data with an exact duration conversion; canonical validation rejects nonpositive or fractional milliseconds.
func NewUpload(argEndpoint string, argMaxBytes json.Number, argTimeout time.Duration, opts ...UploadOption) *ahp.ContentUpload {
	return NewUploadMilliseconds(argEndpoint, argMaxBytes, durationMilliseconds(argTimeout), opts...)
}

// NewUploadDuration checks and converts a duration before constructing the subscription.
func NewUploadDuration(argEndpoint string, argMaxBytes json.Number, argTimeout time.Duration, opts ...UploadOption) (*ahp.ContentUpload, error) {
	argTimeoutMs, err := Milliseconds(argTimeout)
	if err != nil {
		var zero *ahp.ContentUpload
		return zero, err
	}
	return NewUploadMilliseconds(argEndpoint, argMaxBytes, argTimeoutMs, opts...), nil
}

// Milliseconds converts a positive, whole-millisecond duration without truncation.
// It does not apply a default or round fractions. Protocol validation remains required.
// durationMilliseconds is total: preserve invalid fractional/negative values
// exactly so canonical validation can reject them, never silently round them.
func durationMilliseconds(value time.Duration) json.Number {
	whole, fraction := int64(value/time.Millisecond), int64(value%time.Millisecond)
	if fraction == 0 {
		return json.Number(strconv.FormatInt(whole, 10))
	}
	sign := ""
	if value < 0 {
		sign = "-"
		whole = -whole
		fraction = -fraction
	}
	return json.Number(strings.TrimRight(fmt.Sprintf("%s%d.%06d", sign, whole, fraction), "0"))
}
func Milliseconds(value time.Duration) (json.Number, error) {
	if value <= 0 || value%time.Millisecond != 0 {
		return "", fmt.Errorf("timeout must be positive whole milliseconds")
	}
	return json.Number(strconv.FormatInt(int64(value/time.Millisecond), 10)), nil
}
