// Code generated by ahp-codegen. DO NOT EDIT.
package registration

import ahp "github.com/agenthooksprotocol/go-sdk"

type BackendOption func(*ahp.Backend)

func WithBackendAuthentication(value *ahp.Authentication) BackendOption {
	return func(v *ahp.Backend) {
		v.Authentication = ahp.Optional[*ahp.Authentication]{Present: true, Value: value}
	}
}
func WithBackendSubscriptions(values ...ahp.BackendSubscriptionsItem) BackendOption {
	return func(v *ahp.Backend) { v.Subscriptions = append([]ahp.BackendSubscriptionsItem{}, values...) }
}
func NewBackend(argID string, argTransport ahp.BackendTransport, argSubscriptions ahp.BackendSubscriptionsItem, opts ...BackendOption) *ahp.Backend {
	v := &ahp.Backend{ID: &argID, Transport: argTransport, Subscriptions: []ahp.BackendSubscriptionsItem{argSubscriptions}}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type Option func(*ahp.Registration)

func New(argHooks ...*ahp.Backend) ahp.Registration {
	v := &ahp.Registration{Hooks: argHooks, ProtocolVersion: func() *ahp.ProtocolVersion { v := ahp.ProtocolVersion("draft"); return &v }()}
	return *v
}
