// Code generated by ahp-codegen. DO NOT EDIT.
package transport

import ahp "github.com/agenthooksprotocol/go-sdk"

type HttpOption func(*ahp.HttpTransport)

func NewHttp(argURL string, opts ...HttpOption) ahp.BackendTransport {
	v := &ahp.HttpTransport{Type: "http", URL: argURL}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return ahp.BackendTransport{HttpTransport: ahp.Optional[*ahp.HttpTransport]{Present: true, Value: v}}
}

type StdioOption func(*ahp.StdioTransport)

func WithStdioArgs(value []string) StdioOption {
	return func(v *ahp.StdioTransport) { v.Args = ahp.Optional[[]string]{Present: true, Value: value} }
}
func WithStdioCWD(value string) StdioOption {
	return func(v *ahp.StdioTransport) { v.CWD = ahp.Optional[string]{Present: true, Value: value} }
}
func NewStdio(argCommand string, argLifecycle ahp.StdioTransportLifecycle, opts ...StdioOption) ahp.BackendTransport {
	v := &ahp.StdioTransport{Command: argCommand, Lifecycle: argLifecycle, Type: "stdio"}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return ahp.BackendTransport{StdioTransport: ahp.Optional[*ahp.StdioTransport]{Present: true, Value: v}}
}
