// Code generated by ahp-codegen. DO NOT EDIT.
package subscription

import ahp "github.com/agenthooksprotocol/go-sdk"
import "encoding/json"
import "time"
import "fmt"
import "strconv"
import "strings"

type InterceptOption func(*ahp.InterceptSubscription)

func WithInterceptDisableable(value bool) InterceptOption {
	return func(v *ahp.InterceptSubscription) { v.Disableable = ahp.Optional[bool]{Present: true, Value: value} }
}
func WithInterceptFilters(value ahp.InterceptSubscriptionFilters) InterceptOption {
	return func(v *ahp.InterceptSubscription) {
		v.Filters = ahp.Optional[ahp.InterceptSubscriptionFilters]{Present: true, Value: value}
	}
}
func WithInterceptIncludeNative(value bool) InterceptOption {
	return func(v *ahp.InterceptSubscription) { v.IncludeNative = ahp.Optional[bool]{Present: true, Value: value} }
}
func WithInterceptScope(value ahp.InterceptSubscriptionScope) InterceptOption {
	return func(v *ahp.InterceptSubscription) {
		v.Scope = ahp.Optional[ahp.InterceptSubscriptionScope]{Present: true, Value: value}
	}
}
func WithInterceptUpload(value *ahp.ContentUpload) InterceptOption {
	return func(v *ahp.InterceptSubscription) {
		v.Upload = ahp.Optional[*ahp.ContentUpload]{Present: true, Value: value}
	}
}
func WithInterceptEvents(values ...ahp.InterceptSubscriptionEventsItem) InterceptOption {
	return func(v *ahp.InterceptSubscription) {
		v.Events = append([]ahp.InterceptSubscriptionEventsItem{}, values...)
	}
}
func NewInterceptMilliseconds(argEvents []string, argTimeoutMs json.Number, argFailurePolicy ahp.InterceptSubscriptionFailurePolicy, argContent *ahp.ContentSelection, opts ...InterceptOption) ahp.BackendSubscriptionsItem {
	v := &ahp.InterceptSubscription{Events: func() []ahp.InterceptSubscriptionEventsItem {
		values := make([]ahp.InterceptSubscriptionEventsItem, len(argEvents))
		for i, value := range argEvents {
			values[i] = ahp.InterceptSubscriptionEventsItem{Variant2: ahp.Optional[string]{Present: true, Value: value}}
		}
		return values
	}(), TimeoutMs: argTimeoutMs, FailurePolicy: argFailurePolicy, Content: argContent, Mode: "intercept", IncludeNative: ahp.Optional[bool]{Present: true, Value: bool(false)}}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return ahp.BackendSubscriptionsItem{InterceptSubscription: ahp.Optional[*ahp.InterceptSubscription]{Present: true, Value: v}}
}

// NewIntercept constructs data with an exact duration conversion; canonical validation rejects nonpositive or fractional milliseconds.
func NewIntercept(argEvents []string, argTimeout time.Duration, argFailurePolicy ahp.InterceptSubscriptionFailurePolicy, argContent *ahp.ContentSelection, opts ...InterceptOption) ahp.BackendSubscriptionsItem {
	return NewInterceptMilliseconds(argEvents, durationMilliseconds(argTimeout), argFailurePolicy, argContent, opts...)
}

// NewInterceptDuration checks and converts a duration before constructing the subscription.
func NewInterceptDuration(argEvents []string, argTimeout time.Duration, argFailurePolicy ahp.InterceptSubscriptionFailurePolicy, argContent *ahp.ContentSelection, opts ...InterceptOption) (ahp.BackendSubscriptionsItem, error) {
	argTimeoutMs, err := Milliseconds(argTimeout)
	if err != nil {
		var zero ahp.BackendSubscriptionsItem
		return zero, err
	}
	return NewInterceptMilliseconds(argEvents, argTimeoutMs, argFailurePolicy, argContent, opts...), nil
}

type ObserveOption func(*ahp.ObserveSubscription)

func WithObserveDisableable(value bool) ObserveOption {
	return func(v *ahp.ObserveSubscription) { v.Disableable = ahp.Optional[bool]{Present: true, Value: value} }
}
func WithObserveFilters(value ahp.ObserveSubscriptionFilters) ObserveOption {
	return func(v *ahp.ObserveSubscription) {
		v.Filters = ahp.Optional[ahp.ObserveSubscriptionFilters]{Present: true, Value: value}
	}
}
func WithObserveIncludeNative(value bool) ObserveOption {
	return func(v *ahp.ObserveSubscription) { v.IncludeNative = ahp.Optional[bool]{Present: true, Value: value} }
}
func WithObserveScope(value ahp.ObserveSubscriptionScope) ObserveOption {
	return func(v *ahp.ObserveSubscription) {
		v.Scope = ahp.Optional[ahp.ObserveSubscriptionScope]{Present: true, Value: value}
	}
}
func WithObserveUpload(value *ahp.ContentUpload) ObserveOption {
	return func(v *ahp.ObserveSubscription) {
		v.Upload = ahp.Optional[*ahp.ContentUpload]{Present: true, Value: value}
	}
}
func WithObserveEvents(values ...ahp.ObserveSubscriptionEventsItem) ObserveOption {
	return func(v *ahp.ObserveSubscription) { v.Events = append([]ahp.ObserveSubscriptionEventsItem{}, values...) }
}
func NewObserve(argContent *ahp.ContentSelection, argEvents []string, opts ...ObserveOption) ahp.BackendSubscriptionsItem {
	v := &ahp.ObserveSubscription{Content: argContent, Events: func() []ahp.ObserveSubscriptionEventsItem {
		values := make([]ahp.ObserveSubscriptionEventsItem, len(argEvents))
		for i, value := range argEvents {
			values[i] = ahp.ObserveSubscriptionEventsItem{Variant2: ahp.Optional[string]{Present: true, Value: value}}
		}
		return values
	}(), Mode: "observe", IncludeNative: ahp.Optional[bool]{Present: true, Value: bool(false)}}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return ahp.BackendSubscriptionsItem{ObserveSubscription: ahp.Optional[*ahp.ObserveSubscription]{Present: true, Value: v}}
}

// Milliseconds converts a positive, whole-millisecond duration without truncation.
// It does not apply a default or round fractions. Protocol validation remains required.
// durationMilliseconds is total: preserve invalid fractional/negative values
// exactly so canonical validation can reject them, never silently round them.
func durationMilliseconds(value time.Duration) json.Number {
	whole, fraction := int64(value/time.Millisecond), int64(value%time.Millisecond)
	if fraction == 0 {
		return json.Number(strconv.FormatInt(whole, 10))
	}
	sign := ""
	if value < 0 {
		sign = "-"
		whole = -whole
		fraction = -fraction
	}
	return json.Number(strings.TrimRight(fmt.Sprintf("%s%d.%06d", sign, whole, fraction), "0"))
}
func Milliseconds(value time.Duration) (json.Number, error) {
	if value <= 0 || value%time.Millisecond != 0 {
		return "", fmt.Errorf("timeout must be positive whole milliseconds")
	}
	return json.Number(strconv.FormatInt(int64(value/time.Millisecond), 10)), nil
}
