// Code generated by ahp-codegen. DO NOT EDIT.
package state

import ahp "github.com/agenthooksprotocol/go-sdk"
import "encoding/json"
import "fmt"
import "github.com/agenthooksprotocol/go-sdk/permission"

type Option func(*ahp.InterceptRequestParamsState)

func WithFlow(value ahp.InterceptRequestParamsStateFlow) Option {
	return func(v *ahp.InterceptRequestParamsState) {
		v.Flow = ahp.Optional[ahp.InterceptRequestParamsStateFlow]{Present: true, Value: value}
	}
}
func WithInjections(value []json.RawMessage) Option {
	return func(v *ahp.InterceptRequestParamsState) {
		v.Injections = ahp.Optional[[]json.RawMessage]{Present: true, Value: value}
	}
}
func WithInstructions(value []string) Option {
	return func(v *ahp.InterceptRequestParamsState) {
		v.Instructions = ahp.Optional[[]string]{Present: true, Value: value}
	}
}
func New(argCandidate ahp.InterceptRequestParamsStateCandidate, argPermission ahp.InterceptRequestParamsStatePermission, opts ...Option) *ahp.InterceptRequestParamsState {
	v := &ahp.InterceptRequestParamsState{Candidate: argCandidate, Permission: argPermission}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

// Initial represents a native decision already made for this occurrence, not authorization.
func Initial(value permission.Permission, opts ...Option) *ahp.InterceptRequestParamsState {
	v := &ahp.InterceptRequestParamsState{Permission: value, Candidate: NoCandidate()}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}
func NoCandidate() ahp.InterceptRequestParamsStateCandidate {
	return ahp.InterceptRequestParamsStateCandidate{Variant1: ahp.Some(json.RawMessage("null"))}
}

// Candidate preserves payload encoding errors instead of silently dropping the value.
func Candidate[T any](value T, provenance ...ahp.InterceptRequestParamsStateCandidateVariant2Provenance) (ahp.InterceptRequestParamsStateCandidate, error) {
	if len(provenance) > 1 {
		return ahp.InterceptRequestParamsStateCandidate{}, fmt.Errorf("candidate accepts at most one provenance")
	}
	raw, err := json.Marshal(value)
	if err != nil {
		return ahp.InterceptRequestParamsStateCandidate{}, err
	}
	candidate := ahp.InterceptRequestParamsStateCandidateVariant2{Value: raw}
	if len(provenance) == 1 {
		candidate.Provenance = ahp.Some(provenance[0])
	}
	return ahp.InterceptRequestParamsStateCandidate{Variant2: ahp.Some(candidate)}, nil
}
func WithCandidate(value ahp.InterceptRequestParamsStateCandidate) Option {
	return func(v *ahp.InterceptRequestParamsState) { v.Candidate = value }
}
