// Code generated by ahp-codegen. DO NOT EDIT.
package tool

import ahp "github.com/agenthooksprotocol/go-sdk"
import "encoding/json"

type Input[T any] struct {
	Input  T                                    `json:"input"`
	Kind   ahp.Optional[string]                 `json:"kind"`
	Mcp    ahp.Optional[*ahp.ExecutionEventMcp] `json:"mcp"`
	Name   string                               `json:"name"`
	Origin ahp.ExecutionEventToolOrigin         `json:"origin"`
}

func (v Input[T]) MarshalJSON() ([]byte, error) {
	fields := map[string]any{}
	fields["input"] = v.Input
	if v.Kind.Present {
		fields["kind"] = v.Kind.Value
	}
	if v.Mcp.Present {
		fields["mcp"] = v.Mcp.Value
	}
	fields["name"] = v.Name
	fields["origin"] = v.Origin
	return json.Marshal(fields)
}

type inputOptions struct {
	Kind ahp.Optional[string]
	Mcp  ahp.Optional[*ahp.ExecutionEventMcp]
}
type InputOption func(*inputOptions)

func WithInputKind(value string) InputOption {
	return func(v *inputOptions) { v.Kind = ahp.Optional[string]{Present: true, Value: value} }
}
func WithInputMcp(value *ahp.ExecutionEventMcp) InputOption {
	return func(v *inputOptions) { v.Mcp = ahp.Optional[*ahp.ExecutionEventMcp]{Present: true, Value: value} }
}

// NewInput preserves the caller's payload type; options set only declared metadata.
func NewInput[T any](argName string, argOrigin ahp.ExecutionEventToolOrigin, argInput T, opts ...InputOption) Input[T] {
	config := inputOptions{}
	for _, opt := range opts {
		if opt != nil {
			opt(&config)
		}
	}
	return Input[T]{Name: argName, Origin: argOrigin, Input: argInput, Kind: config.Kind, Mcp: config.Mcp}
}
