// Code generated by ahp-codegen. DO NOT EDIT.
package permission

import ahp "github.com/agenthooksprotocol/go-sdk"

type Permission = ahp.InterceptRequestParamsStatePermission

const Allow Permission = "allow"
const Ask Permission = "ask"
const Deny Permission = "deny"
const None Permission = "none"
