// Code generated by ahp-codegen. DO NOT EDIT.
package capability

import ahp "github.com/agenthooksprotocol/go-sdk"
import "encoding/json"
import "strconv"
import "fmt"

type Option func(*ahp.Capabilities)

func WithElicitation(value ahp.CapabilitiesElicitation) Option {
	return func(v *ahp.Capabilities) {
		v.Elicitation = ahp.Optional[ahp.CapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithFlow(value ahp.CapabilitiesFlow) Option {
	return func(v *ahp.Capabilities) { v.Flow = ahp.Optional[ahp.CapabilitiesFlow]{Present: true, Value: value} }
}
func WithInject(value ahp.CapabilitiesInject) Option {
	return func(v *ahp.Capabilities) {
		v.Inject = ahp.Optional[ahp.CapabilitiesInject]{Present: true, Value: value}
	}
}
func WithModify(value ahp.CapabilitiesModify) Option {
	return func(v *ahp.Capabilities) {
		v.Modify = ahp.Optional[ahp.CapabilitiesModify]{Present: true, Value: value}
	}
}
func WithEffects(values ...string) Option {
	return func(v *ahp.Capabilities) {
		v.Effects = func() []ahp.CapabilitiesEffectsItem {
			items := make([]ahp.CapabilitiesEffectsItem, len(values))
			for i, value := range values {
				items[i] = ahp.CapabilitiesEffectsItem{Variant2: ahp.Optional[string]{Present: true, Value: value}}
			}
			return items
		}()
	}
}
func New(argEffects []string, opts ...Option) *ahp.Capabilities {
	v := &ahp.Capabilities{Effects: func() []ahp.CapabilitiesEffectsItem {
		items := make([]ahp.CapabilitiesEffectsItem, len(argEffects))
		for i, value := range argEffects {
			items[i] = ahp.CapabilitiesEffectsItem{Variant2: ahp.Optional[string]{Present: true, Value: value}}
		}
		return items
	}()}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ConfigChangeBeforeOption func(*ahp.ConfigChangeBeforeCapabilities)

func WithConfigChangeBeforeElicitation(value ahp.ConfigChangeBeforeCapabilitiesElicitation) ConfigChangeBeforeOption {
	return func(v *ahp.ConfigChangeBeforeCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ConfigChangeBeforeCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithConfigChangeBeforeFlow(value ahp.ConfigChangeBeforeCapabilitiesFlow) ConfigChangeBeforeOption {
	return func(v *ahp.ConfigChangeBeforeCapabilities) {
		v.Flow = ahp.Optional[ahp.ConfigChangeBeforeCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithConfigChangeBeforeInject(value ahp.ConfigChangeBeforeCapabilitiesInject) ConfigChangeBeforeOption {
	return func(v *ahp.ConfigChangeBeforeCapabilities) {
		v.Inject = ahp.Optional[ahp.ConfigChangeBeforeCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithConfigChangeBeforeModify(value ahp.ConfigChangeBeforeCapabilitiesModify) ConfigChangeBeforeOption {
	return func(v *ahp.ConfigChangeBeforeCapabilities) {
		v.Modify = ahp.Optional[ahp.ConfigChangeBeforeCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewConfigChangeBefore(argEffects json.RawMessage, opts ...ConfigChangeBeforeOption) *ahp.ConfigChangeBeforeCapabilities {
	v := &ahp.ConfigChangeBeforeCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ContextCompactAfterOption func(*ahp.ContextCompactAfterCapabilities)

func WithContextCompactAfterElicitation(value ahp.ContextCompactAfterCapabilitiesElicitation) ContextCompactAfterOption {
	return func(v *ahp.ContextCompactAfterCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ContextCompactAfterCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithContextCompactAfterFlow(value ahp.ContextCompactAfterCapabilitiesFlow) ContextCompactAfterOption {
	return func(v *ahp.ContextCompactAfterCapabilities) {
		v.Flow = ahp.Optional[ahp.ContextCompactAfterCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithContextCompactAfterInject(value ahp.ContextCompactAfterCapabilitiesInject) ContextCompactAfterOption {
	return func(v *ahp.ContextCompactAfterCapabilities) {
		v.Inject = ahp.Optional[ahp.ContextCompactAfterCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithContextCompactAfterModify(value ahp.ContextCompactAfterCapabilitiesModify) ContextCompactAfterOption {
	return func(v *ahp.ContextCompactAfterCapabilities) {
		v.Modify = ahp.Optional[ahp.ContextCompactAfterCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewContextCompactAfter(argEffects json.RawMessage, opts ...ContextCompactAfterOption) *ahp.ContextCompactAfterCapabilities {
	v := &ahp.ContextCompactAfterCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ContextCompactBeforeOption func(*ahp.ContextCompactBeforeCapabilities)

func WithContextCompactBeforeElicitation(value ahp.ContextCompactBeforeCapabilitiesElicitation) ContextCompactBeforeOption {
	return func(v *ahp.ContextCompactBeforeCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ContextCompactBeforeCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithContextCompactBeforeFlow(value ahp.ContextCompactBeforeCapabilitiesFlow) ContextCompactBeforeOption {
	return func(v *ahp.ContextCompactBeforeCapabilities) {
		v.Flow = ahp.Optional[ahp.ContextCompactBeforeCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithContextCompactBeforeInject(value ahp.ContextCompactBeforeCapabilitiesInject) ContextCompactBeforeOption {
	return func(v *ahp.ContextCompactBeforeCapabilities) {
		v.Inject = ahp.Optional[ahp.ContextCompactBeforeCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithContextCompactBeforeModify(value ahp.ContextCompactBeforeCapabilitiesModify) ContextCompactBeforeOption {
	return func(v *ahp.ContextCompactBeforeCapabilities) {
		v.Modify = ahp.Optional[ahp.ContextCompactBeforeCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewContextCompactBefore(argEffects json.RawMessage, opts ...ContextCompactBeforeOption) *ahp.ContextCompactBeforeCapabilities {
	v := &ahp.ContextCompactBeforeCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ModelRequestBeforeOption func(*ahp.ModelRequestBeforeCapabilities)

func WithModelRequestBeforeElicitation(value ahp.ModelRequestBeforeCapabilitiesElicitation) ModelRequestBeforeOption {
	return func(v *ahp.ModelRequestBeforeCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ModelRequestBeforeCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithModelRequestBeforeFlow(value ahp.ModelRequestBeforeCapabilitiesFlow) ModelRequestBeforeOption {
	return func(v *ahp.ModelRequestBeforeCapabilities) {
		v.Flow = ahp.Optional[ahp.ModelRequestBeforeCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithModelRequestBeforeInject(value ahp.ModelRequestBeforeCapabilitiesInject) ModelRequestBeforeOption {
	return func(v *ahp.ModelRequestBeforeCapabilities) {
		v.Inject = ahp.Optional[ahp.ModelRequestBeforeCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithModelRequestBeforeModify(value ahp.ModelRequestBeforeCapabilitiesModify) ModelRequestBeforeOption {
	return func(v *ahp.ModelRequestBeforeCapabilities) {
		v.Modify = ahp.Optional[ahp.ModelRequestBeforeCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewModelRequestBefore(argEffects json.RawMessage, opts ...ModelRequestBeforeOption) *ahp.ModelRequestBeforeCapabilities {
	v := &ahp.ModelRequestBeforeCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ModelResponseAfterOption func(*ahp.ModelResponseAfterCapabilities)

func WithModelResponseAfterElicitation(value ahp.ModelResponseAfterCapabilitiesElicitation) ModelResponseAfterOption {
	return func(v *ahp.ModelResponseAfterCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ModelResponseAfterCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithModelResponseAfterFlow(value ahp.ModelResponseAfterCapabilitiesFlow) ModelResponseAfterOption {
	return func(v *ahp.ModelResponseAfterCapabilities) {
		v.Flow = ahp.Optional[ahp.ModelResponseAfterCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithModelResponseAfterInject(value ahp.ModelResponseAfterCapabilitiesInject) ModelResponseAfterOption {
	return func(v *ahp.ModelResponseAfterCapabilities) {
		v.Inject = ahp.Optional[ahp.ModelResponseAfterCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithModelResponseAfterModify(value ahp.ModelResponseAfterCapabilitiesModify) ModelResponseAfterOption {
	return func(v *ahp.ModelResponseAfterCapabilities) {
		v.Modify = ahp.Optional[ahp.ModelResponseAfterCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewModelResponseAfter(argEffects json.RawMessage, opts ...ModelResponseAfterOption) *ahp.ModelResponseAfterCapabilities {
	v := &ahp.ModelResponseAfterCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ModelSwitchBeforeOption func(*ahp.ModelSwitchBeforeCapabilities)

func WithModelSwitchBeforeElicitation(value ahp.ModelSwitchBeforeCapabilitiesElicitation) ModelSwitchBeforeOption {
	return func(v *ahp.ModelSwitchBeforeCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ModelSwitchBeforeCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithModelSwitchBeforeFlow(value ahp.ModelSwitchBeforeCapabilitiesFlow) ModelSwitchBeforeOption {
	return func(v *ahp.ModelSwitchBeforeCapabilities) {
		v.Flow = ahp.Optional[ahp.ModelSwitchBeforeCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithModelSwitchBeforeInject(value ahp.ModelSwitchBeforeCapabilitiesInject) ModelSwitchBeforeOption {
	return func(v *ahp.ModelSwitchBeforeCapabilities) {
		v.Inject = ahp.Optional[ahp.ModelSwitchBeforeCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithModelSwitchBeforeModify(value ahp.ModelSwitchBeforeCapabilitiesModify) ModelSwitchBeforeOption {
	return func(v *ahp.ModelSwitchBeforeCapabilities) {
		v.Modify = ahp.Optional[ahp.ModelSwitchBeforeCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewModelSwitchBefore(argEffects json.RawMessage, opts ...ModelSwitchBeforeOption) *ahp.ModelSwitchBeforeCapabilities {
	v := &ahp.ModelSwitchBeforeCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type SessionStartOption func(*ahp.SessionStartCapabilities)

func WithSessionStartElicitation(value ahp.SessionStartCapabilitiesElicitation) SessionStartOption {
	return func(v *ahp.SessionStartCapabilities) {
		v.Elicitation = ahp.Optional[ahp.SessionStartCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithSessionStartFlow(value ahp.SessionStartCapabilitiesFlow) SessionStartOption {
	return func(v *ahp.SessionStartCapabilities) {
		v.Flow = ahp.Optional[ahp.SessionStartCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithSessionStartInject(value ahp.SessionStartCapabilitiesInject) SessionStartOption {
	return func(v *ahp.SessionStartCapabilities) {
		v.Inject = ahp.Optional[ahp.SessionStartCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithSessionStartModify(value ahp.SessionStartCapabilitiesModify) SessionStartOption {
	return func(v *ahp.SessionStartCapabilities) {
		v.Modify = ahp.Optional[ahp.SessionStartCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewSessionStart(argEffects json.RawMessage, opts ...SessionStartOption) *ahp.SessionStartCapabilities {
	v := &ahp.SessionStartCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type StaticCapabilityManifestOption func(*ahp.StaticCapabilityManifest)

func WithStaticCapabilityManifestAuthentication(values ...ahp.StaticCapabilityManifestAuthenticationItem) StaticCapabilityManifestOption {
	return func(v *ahp.StaticCapabilityManifest) {
		v.Authentication = append([]ahp.StaticCapabilityManifestAuthenticationItem{}, values...)
	}
}
func WithStaticCapabilityManifestContentCategories(values ...string) StaticCapabilityManifestOption {
	return func(v *ahp.StaticCapabilityManifest) { v.ContentCategories = append([]string{}, values...) }
}
func WithStaticCapabilityManifestCorrelationIdentityFields(values ...string) StaticCapabilityManifestOption {
	return func(v *ahp.StaticCapabilityManifest) { v.CorrelationIdentityFields = append([]string{}, values...) }
}
func WithStaticCapabilityManifestEvents(values ...ahp.StaticCapabilityManifestEventsItem) StaticCapabilityManifestOption {
	return func(v *ahp.StaticCapabilityManifest) {
		v.Events = append([]ahp.StaticCapabilityManifestEventsItem{}, values...)
	}
}
func WithStaticCapabilityManifestGaps(values ...ahp.StaticCapabilityManifestGapsItem) StaticCapabilityManifestOption {
	return func(v *ahp.StaticCapabilityManifest) {
		v.Gaps = append([]ahp.StaticCapabilityManifestGapsItem{}, values...)
	}
}
func WithStaticCapabilityManifestToolPaths(values ...string) StaticCapabilityManifestOption {
	return func(v *ahp.StaticCapabilityManifest) { v.ToolPaths = append([]string{}, values...) }
}
func WithStaticCapabilityManifestTransports(values ...ahp.StaticCapabilityManifestTransportsItem) StaticCapabilityManifestOption {
	return func(v *ahp.StaticCapabilityManifest) {
		v.Transports = append([]ahp.StaticCapabilityManifestTransportsItem{}, values...)
	}
}
func NewStaticCapabilityManifest(argAuthentication []ahp.StaticCapabilityManifestAuthenticationItem, argContentCategories []string, argCorrelationIdentityFields []string, argEvents []ahp.StaticCapabilityManifestEventsItem, argGaps []ahp.StaticCapabilityManifestGapsItem, argLimits ahp.StaticCapabilityManifestLimits, argManagedPolicy ahp.StaticCapabilityManifestManagedPolicy, argToolPaths []string, argTransports []ahp.StaticCapabilityManifestTransportsItem, opts ...StaticCapabilityManifestOption) *ahp.StaticCapabilityManifest {
	v := &ahp.StaticCapabilityManifest{Authentication: argAuthentication, ContentCategories: argContentCategories, CorrelationIdentityFields: argCorrelationIdentityFields, Events: argEvents, Gaps: argGaps, Limits: argLimits, ManagedPolicy: argManagedPolicy, ToolPaths: argToolPaths, Transports: argTransports}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type TaskChangeBeforeOption func(*ahp.TaskChangeBeforeCapabilities)

func WithTaskChangeBeforeElicitation(value ahp.TaskChangeBeforeCapabilitiesElicitation) TaskChangeBeforeOption {
	return func(v *ahp.TaskChangeBeforeCapabilities) {
		v.Elicitation = ahp.Optional[ahp.TaskChangeBeforeCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithTaskChangeBeforeFlow(value ahp.TaskChangeBeforeCapabilitiesFlow) TaskChangeBeforeOption {
	return func(v *ahp.TaskChangeBeforeCapabilities) {
		v.Flow = ahp.Optional[ahp.TaskChangeBeforeCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithTaskChangeBeforeInject(value ahp.TaskChangeBeforeCapabilitiesInject) TaskChangeBeforeOption {
	return func(v *ahp.TaskChangeBeforeCapabilities) {
		v.Inject = ahp.Optional[ahp.TaskChangeBeforeCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithTaskChangeBeforeModify(value ahp.TaskChangeBeforeCapabilitiesModify) TaskChangeBeforeOption {
	return func(v *ahp.TaskChangeBeforeCapabilities) {
		v.Modify = ahp.Optional[ahp.TaskChangeBeforeCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewTaskChangeBefore(argEffects json.RawMessage, opts ...TaskChangeBeforeOption) *ahp.TaskChangeBeforeCapabilities {
	v := &ahp.TaskChangeBeforeCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ToolAfterOption func(*ahp.ToolAfterCapabilities)

func WithToolAfterElicitation(value ahp.ToolAfterCapabilitiesElicitation) ToolAfterOption {
	return func(v *ahp.ToolAfterCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ToolAfterCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithToolAfterFlow(value ahp.ToolAfterCapabilitiesFlow) ToolAfterOption {
	return func(v *ahp.ToolAfterCapabilities) {
		v.Flow = ahp.Optional[ahp.ToolAfterCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithToolAfterInject(value ahp.ToolAfterCapabilitiesInject) ToolAfterOption {
	return func(v *ahp.ToolAfterCapabilities) {
		v.Inject = ahp.Optional[ahp.ToolAfterCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithToolAfterModify(value ahp.ToolAfterCapabilitiesModify) ToolAfterOption {
	return func(v *ahp.ToolAfterCapabilities) {
		v.Modify = ahp.Optional[ahp.ToolAfterCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewToolAfter(argEffects json.RawMessage, opts ...ToolAfterOption) *ahp.ToolAfterCapabilities {
	v := &ahp.ToolAfterCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ToolBatchAfterOption func(*ahp.ToolBatchAfterCapabilities)

func WithToolBatchAfterElicitation(value ahp.ToolBatchAfterCapabilitiesElicitation) ToolBatchAfterOption {
	return func(v *ahp.ToolBatchAfterCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ToolBatchAfterCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithToolBatchAfterFlow(value ahp.ToolBatchAfterCapabilitiesFlow) ToolBatchAfterOption {
	return func(v *ahp.ToolBatchAfterCapabilities) {
		v.Flow = ahp.Optional[ahp.ToolBatchAfterCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithToolBatchAfterInject(value ahp.ToolBatchAfterCapabilitiesInject) ToolBatchAfterOption {
	return func(v *ahp.ToolBatchAfterCapabilities) {
		v.Inject = ahp.Optional[ahp.ToolBatchAfterCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithToolBatchAfterModify(value ahp.ToolBatchAfterCapabilitiesModify) ToolBatchAfterOption {
	return func(v *ahp.ToolBatchAfterCapabilities) {
		v.Modify = ahp.Optional[ahp.ToolBatchAfterCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewToolBatchAfter(argEffects json.RawMessage, opts ...ToolBatchAfterOption) *ahp.ToolBatchAfterCapabilities {
	v := &ahp.ToolBatchAfterCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ToolBeforeOption func(*ahp.ToolBeforeCapabilities)

func WithToolBeforeElicitation(value ahp.ToolBeforeCapabilitiesElicitation) ToolBeforeOption {
	return func(v *ahp.ToolBeforeCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ToolBeforeCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithToolBeforeFlow(value ahp.ToolBeforeCapabilitiesFlow) ToolBeforeOption {
	return func(v *ahp.ToolBeforeCapabilities) {
		v.Flow = ahp.Optional[ahp.ToolBeforeCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithToolBeforeInject(value ahp.ToolBeforeCapabilitiesInject) ToolBeforeOption {
	return func(v *ahp.ToolBeforeCapabilities) {
		v.Inject = ahp.Optional[ahp.ToolBeforeCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithToolBeforeModify(value ahp.ToolBeforeCapabilitiesModify) ToolBeforeOption {
	return func(v *ahp.ToolBeforeCapabilities) {
		v.Modify = ahp.Optional[ahp.ToolBeforeCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewToolBefore(argEffects json.RawMessage, opts ...ToolBeforeOption) *ahp.ToolBeforeCapabilities {
	v := &ahp.ToolBeforeCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type ToolPermissionRequestOption func(*ahp.ToolPermissionRequestCapabilities)

func WithToolPermissionRequestElicitation(value ahp.ToolPermissionRequestCapabilitiesElicitation) ToolPermissionRequestOption {
	return func(v *ahp.ToolPermissionRequestCapabilities) {
		v.Elicitation = ahp.Optional[ahp.ToolPermissionRequestCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithToolPermissionRequestFlow(value ahp.ToolPermissionRequestCapabilitiesFlow) ToolPermissionRequestOption {
	return func(v *ahp.ToolPermissionRequestCapabilities) {
		v.Flow = ahp.Optional[ahp.ToolPermissionRequestCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithToolPermissionRequestInject(value ahp.ToolPermissionRequestCapabilitiesInject) ToolPermissionRequestOption {
	return func(v *ahp.ToolPermissionRequestCapabilities) {
		v.Inject = ahp.Optional[ahp.ToolPermissionRequestCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithToolPermissionRequestModify(value ahp.ToolPermissionRequestCapabilitiesModify) ToolPermissionRequestOption {
	return func(v *ahp.ToolPermissionRequestCapabilities) {
		v.Modify = ahp.Optional[ahp.ToolPermissionRequestCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewToolPermissionRequest(argEffects json.RawMessage, opts ...ToolPermissionRequestOption) *ahp.ToolPermissionRequestCapabilities {
	v := &ahp.ToolPermissionRequestCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type TurnFinishBeforeOption func(*ahp.TurnFinishBeforeCapabilities)

func WithTurnFinishBeforeElicitation(value ahp.TurnFinishBeforeCapabilitiesElicitation) TurnFinishBeforeOption {
	return func(v *ahp.TurnFinishBeforeCapabilities) {
		v.Elicitation = ahp.Optional[ahp.TurnFinishBeforeCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithTurnFinishBeforeFlow(value ahp.TurnFinishBeforeCapabilitiesFlow) TurnFinishBeforeOption {
	return func(v *ahp.TurnFinishBeforeCapabilities) {
		v.Flow = ahp.Optional[ahp.TurnFinishBeforeCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithTurnFinishBeforeInject(value ahp.TurnFinishBeforeCapabilitiesInject) TurnFinishBeforeOption {
	return func(v *ahp.TurnFinishBeforeCapabilities) {
		v.Inject = ahp.Optional[ahp.TurnFinishBeforeCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithTurnFinishBeforeModify(value ahp.TurnFinishBeforeCapabilitiesModify) TurnFinishBeforeOption {
	return func(v *ahp.TurnFinishBeforeCapabilities) {
		v.Modify = ahp.Optional[ahp.TurnFinishBeforeCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewTurnFinishBefore(argEffects json.RawMessage, opts ...TurnFinishBeforeOption) *ahp.TurnFinishBeforeCapabilities {
	v := &ahp.TurnFinishBeforeCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type TurnStartOption func(*ahp.TurnStartCapabilities)

func WithTurnStartElicitation(value ahp.TurnStartCapabilitiesElicitation) TurnStartOption {
	return func(v *ahp.TurnStartCapabilities) {
		v.Elicitation = ahp.Optional[ahp.TurnStartCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithTurnStartFlow(value ahp.TurnStartCapabilitiesFlow) TurnStartOption {
	return func(v *ahp.TurnStartCapabilities) {
		v.Flow = ahp.Optional[ahp.TurnStartCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithTurnStartInject(value ahp.TurnStartCapabilitiesInject) TurnStartOption {
	return func(v *ahp.TurnStartCapabilities) {
		v.Inject = ahp.Optional[ahp.TurnStartCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithTurnStartModify(value ahp.TurnStartCapabilitiesModify) TurnStartOption {
	return func(v *ahp.TurnStartCapabilities) {
		v.Modify = ahp.Optional[ahp.TurnStartCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewTurnStart(argEffects json.RawMessage, opts ...TurnStartOption) *ahp.TurnStartCapabilities {
	v := &ahp.TurnStartCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type UserElicitationRequestOption func(*ahp.UserElicitationRequestCapabilities)

func WithUserElicitationRequestElicitation(value ahp.UserElicitationRequestCapabilitiesElicitation) UserElicitationRequestOption {
	return func(v *ahp.UserElicitationRequestCapabilities) {
		v.Elicitation = ahp.Optional[ahp.UserElicitationRequestCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithUserElicitationRequestFlow(value ahp.UserElicitationRequestCapabilitiesFlow) UserElicitationRequestOption {
	return func(v *ahp.UserElicitationRequestCapabilities) {
		v.Flow = ahp.Optional[ahp.UserElicitationRequestCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithUserElicitationRequestInject(value ahp.UserElicitationRequestCapabilitiesInject) UserElicitationRequestOption {
	return func(v *ahp.UserElicitationRequestCapabilities) {
		v.Inject = ahp.Optional[ahp.UserElicitationRequestCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithUserElicitationRequestModify(value ahp.UserElicitationRequestCapabilitiesModify) UserElicitationRequestOption {
	return func(v *ahp.UserElicitationRequestCapabilities) {
		v.Modify = ahp.Optional[ahp.UserElicitationRequestCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewUserElicitationRequest(argEffects json.RawMessage, opts ...UserElicitationRequestOption) *ahp.UserElicitationRequestCapabilities {
	v := &ahp.UserElicitationRequestCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type UserElicitationResultOption func(*ahp.UserElicitationResultCapabilities)

func WithUserElicitationResultElicitation(value ahp.UserElicitationResultCapabilitiesElicitation) UserElicitationResultOption {
	return func(v *ahp.UserElicitationResultCapabilities) {
		v.Elicitation = ahp.Optional[ahp.UserElicitationResultCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithUserElicitationResultFlow(value ahp.UserElicitationResultCapabilitiesFlow) UserElicitationResultOption {
	return func(v *ahp.UserElicitationResultCapabilities) {
		v.Flow = ahp.Optional[ahp.UserElicitationResultCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithUserElicitationResultInject(value ahp.UserElicitationResultCapabilitiesInject) UserElicitationResultOption {
	return func(v *ahp.UserElicitationResultCapabilities) {
		v.Inject = ahp.Optional[ahp.UserElicitationResultCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithUserElicitationResultModify(value ahp.UserElicitationResultCapabilitiesModify) UserElicitationResultOption {
	return func(v *ahp.UserElicitationResultCapabilities) {
		v.Modify = ahp.Optional[ahp.UserElicitationResultCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewUserElicitationResult(argEffects json.RawMessage, opts ...UserElicitationResultOption) *ahp.UserElicitationResultCapabilities {
	v := &ahp.UserElicitationResultCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type UserMessageInboundOption func(*ahp.UserMessageInboundCapabilities)

func WithUserMessageInboundElicitation(value ahp.UserMessageInboundCapabilitiesElicitation) UserMessageInboundOption {
	return func(v *ahp.UserMessageInboundCapabilities) {
		v.Elicitation = ahp.Optional[ahp.UserMessageInboundCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithUserMessageInboundFlow(value ahp.UserMessageInboundCapabilitiesFlow) UserMessageInboundOption {
	return func(v *ahp.UserMessageInboundCapabilities) {
		v.Flow = ahp.Optional[ahp.UserMessageInboundCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithUserMessageInboundInject(value ahp.UserMessageInboundCapabilitiesInject) UserMessageInboundOption {
	return func(v *ahp.UserMessageInboundCapabilities) {
		v.Inject = ahp.Optional[ahp.UserMessageInboundCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithUserMessageInboundModify(value ahp.UserMessageInboundCapabilitiesModify) UserMessageInboundOption {
	return func(v *ahp.UserMessageInboundCapabilities) {
		v.Modify = ahp.Optional[ahp.UserMessageInboundCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewUserMessageInbound(argEffects json.RawMessage, opts ...UserMessageInboundOption) *ahp.UserMessageInboundCapabilities {
	v := &ahp.UserMessageInboundCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type UserMessageOutboundOption func(*ahp.UserMessageOutboundCapabilities)

func WithUserMessageOutboundElicitation(value ahp.UserMessageOutboundCapabilitiesElicitation) UserMessageOutboundOption {
	return func(v *ahp.UserMessageOutboundCapabilities) {
		v.Elicitation = ahp.Optional[ahp.UserMessageOutboundCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithUserMessageOutboundFlow(value ahp.UserMessageOutboundCapabilitiesFlow) UserMessageOutboundOption {
	return func(v *ahp.UserMessageOutboundCapabilities) {
		v.Flow = ahp.Optional[ahp.UserMessageOutboundCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithUserMessageOutboundInject(value ahp.UserMessageOutboundCapabilitiesInject) UserMessageOutboundOption {
	return func(v *ahp.UserMessageOutboundCapabilities) {
		v.Inject = ahp.Optional[ahp.UserMessageOutboundCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithUserMessageOutboundModify(value ahp.UserMessageOutboundCapabilitiesModify) UserMessageOutboundOption {
	return func(v *ahp.UserMessageOutboundCapabilities) {
		v.Modify = ahp.Optional[ahp.UserMessageOutboundCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewUserMessageOutbound(argEffects json.RawMessage, opts ...UserMessageOutboundOption) *ahp.UserMessageOutboundCapabilities {
	v := &ahp.UserMessageOutboundCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

type WorkspaceChangeBeforeOption func(*ahp.WorkspaceChangeBeforeCapabilities)

func WithWorkspaceChangeBeforeElicitation(value ahp.WorkspaceChangeBeforeCapabilitiesElicitation) WorkspaceChangeBeforeOption {
	return func(v *ahp.WorkspaceChangeBeforeCapabilities) {
		v.Elicitation = ahp.Optional[ahp.WorkspaceChangeBeforeCapabilitiesElicitation]{Present: true, Value: value}
	}
}
func WithWorkspaceChangeBeforeFlow(value ahp.WorkspaceChangeBeforeCapabilitiesFlow) WorkspaceChangeBeforeOption {
	return func(v *ahp.WorkspaceChangeBeforeCapabilities) {
		v.Flow = ahp.Optional[ahp.WorkspaceChangeBeforeCapabilitiesFlow]{Present: true, Value: value}
	}
}
func WithWorkspaceChangeBeforeInject(value ahp.WorkspaceChangeBeforeCapabilitiesInject) WorkspaceChangeBeforeOption {
	return func(v *ahp.WorkspaceChangeBeforeCapabilities) {
		v.Inject = ahp.Optional[ahp.WorkspaceChangeBeforeCapabilitiesInject]{Present: true, Value: value}
	}
}
func WithWorkspaceChangeBeforeModify(value ahp.WorkspaceChangeBeforeCapabilitiesModify) WorkspaceChangeBeforeOption {
	return func(v *ahp.WorkspaceChangeBeforeCapabilities) {
		v.Modify = ahp.Optional[ahp.WorkspaceChangeBeforeCapabilitiesModify]{Present: true, Value: value}
	}
}
func NewWorkspaceChangeBefore(argEffects json.RawMessage, opts ...WorkspaceChangeBeforeOption) *ahp.WorkspaceChangeBeforeCapabilities {
	v := &ahp.WorkspaceChangeBeforeCapabilities{Effects: argEffects}
	for _, opt := range opts {
		if opt != nil {
			opt(v)
		}
	}
	return v
}

// WithElicitationForm grants only the declared nested capability; it never adds effects or modes.
func WithElicitationForm() Option {
	return func(v *ahp.Capabilities) {
		v.Elicitation.Present = true
		v.Elicitation.Value.Form = ahp.Optional[ahp.CapabilitiesElicitationForm]{Present: true, Value: ahp.CapabilitiesElicitationForm{}}
	}
}

// WithElicitationURL grants only the declared nested capability; it never adds effects or modes.
func WithElicitationURL() Option {
	return func(v *ahp.Capabilities) {
		v.Elicitation.Present = true
		v.Elicitation.Value.URL = ahp.Optional[ahp.CapabilitiesElicitationURL]{Present: true, Value: ahp.CapabilitiesElicitationURL{}}
	}
}

// WithContentModification grants only the declared nested capability; it never adds effects or modes.
func WithContentModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Content = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

// WithInputModification grants only the declared nested capability; it never adds effects or modes.
func WithInputModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Input = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

// WithInstructionsModification grants only the declared nested capability; it never adds effects or modes.
func WithInstructionsModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Instructions = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

// WithOutputModification grants only the declared nested capability; it never adds effects or modes.
func WithOutputModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Output = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

// WithPromptModification grants only the declared nested capability; it never adds effects or modes.
func WithPromptModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Prompt = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

// WithRequestModification grants only the declared nested capability; it never adds effects or modes.
func WithRequestModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Request = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

// WithResponseModification grants only the declared nested capability; it never adds effects or modes.
func WithResponseModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Response = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

// WithSummaryModification grants only the declared nested capability; it never adds effects or modes.
func WithSummaryModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Summary = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

// WithWorkspaceModification grants only the declared nested capability; it never adds effects or modes.
func WithWorkspaceModification(argReplace bool, argMerge bool) Option {
	return func(v *ahp.Capabilities) {
		v.Modify.Present = true
		v.Modify.Value.Workspace = ahp.Optional[json.RawMessage]{Present: true, Value: json.RawMessage("{" + "\"replace\":" + strconv.FormatBool(argReplace) + ",\"merge\":" + strconv.FormatBool(argMerge) + "}")}
	}
}

type Mode = ahp.StaticCapabilityManifestEventsItemModesItem

const (
	InterceptMode Mode = "intercept"
	ObserveMode   Mode = "observe"
)

type Event struct {
	Modes        []Mode
	Capabilities *ahp.Capabilities
}
type Grant struct{ apply func(*ahp.Capabilities) error }
type ModifyOperation string

// Intercept advertises both modes. It does not authorize host execution.
// The SDK must validate event compatibility and per-call narrowing before delivery.
func Intercept(grants ...Grant) (Event, error) {
	if len(grants) == 0 {
		return Event{}, fmt.Errorf("intercept requires explicit grants")
	}
	value := New([]string{})
	for _, grant := range grants {
		if grant.apply == nil {
			return Event{}, fmt.Errorf("empty capability grant")
		}
		if err := grant.apply(value); err != nil {
			return Event{}, err
		}
	}
	raw, err := json.Marshal(value)
	if err != nil {
		return Event{}, err
	}
	parsed := ahp.ParseCapabilities(raw)
	if !parsed.OK {
		return Event{}, fmt.Errorf("invalid capability declaration: %v", parsed.Diagnostics)
	}
	return Event{Modes: []Mode{InterceptMode, ObserveMode}, Capabilities: value}, nil
}
func Observe() Event { return Event{Modes: []Mode{ObserveMode}} }
func addEffect(v *ahp.Capabilities, name string) {
	for _, effect := range v.Effects {
		if effect.Variant2.Present && effect.Variant2.Value == name {
			return
		}
		if effect.Variant1.Present && string(effect.Variant1.Value) == name {
			return
		}
	}
	v.Effects = append(v.Effects, ahp.CapabilitiesEffectsItem{Variant1: ahp.Some(ahp.CapabilitiesEffectsItemVariant1(name))})
}
func Allow() Grant {
	return Grant{apply: func(v *ahp.Capabilities) error { addEffect(v, "allow"); return nil }}
}
func Ask() Grant {
	return Grant{apply: func(v *ahp.Capabilities) error { addEffect(v, "ask"); return nil }}
}
func Deny() Grant {
	return Grant{apply: func(v *ahp.Capabilities) error { addEffect(v, "deny"); return nil }}
}
func Message() Grant {
	return Grant{apply: func(v *ahp.Capabilities) error { addEffect(v, "message"); return nil }}
}
func Return() Grant {
	return Grant{apply: func(v *ahp.Capabilities) error { addEffect(v, "return"); return nil }}
}

const Merge ModifyOperation = "merge"
const Replace ModifyOperation = "replace"

func ModifyContent(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Content.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Content.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Content = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func ModifyInput(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Input.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Input.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Input = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func ModifyInstructions(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Instructions.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Instructions.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Instructions = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func ModifyOutput(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Output.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Output.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Output = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func ModifyPrompt(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Prompt.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Prompt.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Prompt = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func ModifyRequest(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Request.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Request.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Request = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func ModifyResponse(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Response.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Response.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Response = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func ModifySummary(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Summary.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Summary.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Summary = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func ModifyWorkspace(operations ...ModifyOperation) Grant {
	operations = append([]ModifyOperation(nil), operations...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(operations) == 0 {
			return fmt.Errorf("modification requires an operation")
		}
		flags := map[string]bool{"merge": false, "replace": false}
		for _, operation := range operations {
			if _, known := flags[string(operation)]; !known {
				return fmt.Errorf("unknown modify operation %q", operation)
			}
			flags[string(operation)] = true
		}
		if v.Modify.Present && v.Modify.Value.Workspace.Present {
			var previous map[string]bool
			if err := json.Unmarshal(v.Modify.Value.Workspace.Value, &previous); err != nil {
				return err
			}
			for operation, enabled := range previous {
				flags[operation] = flags[operation] || enabled
			}
		}
		raw, err := json.Marshal(flags)
		if err != nil {
			return err
		}
		v.Modify.Present = true
		v.Modify.Value.Workspace = ahp.Some(json.RawMessage(raw))
		addEffect(v, "modify")
		return nil
	}}
}

func FlowContinue(remaining, count int64) Grant {
	return Grant{apply: func(v *ahp.Capabilities) error {
		if remaining < 0 || count < 0 || remaining > 9007199254740991 || count > 9007199254740991 {
			return fmt.Errorf("continuation counts must be nonnegative safe integers")
		}
		v.Flow.Present = true
		v.Flow.Value.RemainingContinuations = ahp.Some(json.Number(strconv.FormatInt(remaining, 10)))
		v.Flow.Value.ContinuationCount = ahp.Some(json.Number(strconv.FormatInt(count, 10)))
		for _, operation := range v.Flow.Value.Operations {
			if string(operation) == "continue" {
				return nil
			}
		}
		v.Flow.Value.Operations = append(v.Flow.Value.Operations, ahp.CapabilitiesFlowOperationsItem("continue"))
		addEffect(v, "flow")
		return nil
	}}
}
func FlowStop() Grant {
	return Grant{apply: func(v *ahp.Capabilities) error {
		v.Flow.Present = true
		for _, operation := range v.Flow.Value.Operations {
			if string(operation) == "stop" {
				return nil
			}
		}
		v.Flow.Value.Operations = append(v.Flow.Value.Operations, ahp.CapabilitiesFlowOperationsItem("stop"))
		addEffect(v, "flow")
		return nil
	}}
}

type DeliverAt = ahp.CapabilitiesInjectContextDeliverAtItem

const NextTurn DeliverAt = "next_turn"
const Now DeliverAt = "now"

func InjectContextAppend(deliveries ...DeliverAt) Grant {
	deliveries = append([]DeliverAt(nil), deliveries...)
	return Grant{apply: func(v *ahp.Capabilities) error {
		if len(deliveries) == 0 {
			return fmt.Errorf("injection requires explicit delivery timing")
		}
		for _, delivery := range deliveries {
			switch delivery {
			case "next_turn", "now":
			default:
				return fmt.Errorf("invalid injection delivery %q", delivery)
			}
		}
		v.Inject.Present = true
		v.Inject.Value.Context.Append = true
		for _, delivery := range deliveries {
			found := false
			for _, existing := range v.Inject.Value.Context.DeliverAt {
				if existing == delivery {
					found = true
				}
			}
			if !found {
				v.Inject.Value.Context.DeliverAt = append(v.Inject.Value.Context.DeliverAt, delivery)
			}
		}
		addEffect(v, "inject")
		return nil
	}}
}

func ElicitationForm() Grant {
	return Grant{apply: func(v *ahp.Capabilities) error { WithElicitationForm()(v); return nil }}
}
func ElicitationURL() Grant {
	return Grant{apply: func(v *ahp.Capabilities) error { WithElicitationURL()(v); return nil }}
}
